# BinaryBuilder recipe for `tensorprimitives_tapp_jll`.
#
# This file lives in the repository it builds, so the recipe and the source it
# compiles version together. To submit it, copy it verbatim to
# `T/tensorprimitives_tapp/build_tarballs.jl` in a fork of
# https://github.com/JuliaPackaging/Yggdrasil and open a PR titled
# `[tensorprimitives_tapp] Build v0.1.0`.
#
# To dry-run it against uncommitted or untagged work, set TAPP_LOCAL_SRC to a
# directory containing an *export* of the tree (see below) instead of tagging
# something. That switch is the only difference between what is tested here and
# what is submitted; keep it that way.
#
#   git archive --prefix=tensorprimitives-rs-0.1.0/ HEAD \
#     | tar -x -C /tmp/$USER/bb/src
#   TAPP_LOCAL_SRC=/tmp/$USER/bb/src julia --project=... build_tarballs.jl \
#     x86_64-linux-gnu --verbose --debug
#
# `git archive` rather than a copy of the working tree, deliberately: it contains
# tracked files only, so `target/` cannot leak host artifacts into a cross build
# and `Cargo.lock` had better be committed, which `--locked` will confirm loudly.
#
# Run `julia build_tarballs.jl --help` for the argument handling this inherits.

using BinaryBuilder

name = "tensorprimitives_tapp"
version = v"0.1.0"

# `name` must satisfy `Base.isidentifier`, so the hyphenated crate name
# `tensorprimitives-tapp` cannot be used here. It is also the *package* name
# rather than the library name: the library is the `libtensorprimitives_tapp`
# product below.

sources = if haskey(ENV, "TAPP_LOCAL_SRC")
    # Dry-run only. `DirectorySource` copies the directory's *contents* into
    # ${WORKSPACE}/srcdir, so an export at `$TAPP_LOCAL_SRC/tensorprimitives-rs-*`
    # lands where the build script's `cd` glob expects it.
    @warn "building from TAPP_LOCAL_SRC; this is not the submittable form" ENV["TAPP_LOCAL_SRC"]
    [DirectorySource(ENV["TAPP_LOCAL_SRC"])]
else
    [
        # `GitSource` pinned to a commit, and deliberately NOT an archive over
        # `.../archive/refs/tags/v$(version).tar.gz`. BinaryBuilder now **rejects**
        # that URL outright:
        #
        #   ArgumentError: The archive automatically generated by GitHub ... may
        #   not have a stable checksum in the future, thus cannot be used as a
        #   reliable source
        #
        # GitHub does not guarantee its auto-generated archives are byte-stable
        # (github.blog, 2023-02-21). That is a hard error, not a warning, so the
        # form this recipe was originally written with cannot build at all. Do not
        # reintroduce it, and in particular do not try to "fix" it by recomputing
        # the sha256 -- the objection is to the URL, not to the digest.
        #
        # A commit rather than the tag, on purpose: `v0.1.0` was moved twice while
        # the release plumbing was being fixed, and a pin that a tag can relocate
        # under is not a pin.
        GitSource(
            "https://github.com/lkdvos/tensorprimitives-rs.git",
            "ca916fae1947efa526cf7177bf06018c042fd8a6",   # tag v0.1.0
        ),
    ]
end

script = raw"""
# `tensorprimitives-rs*` matches both source forms: `GitSource` checks out into
# `srcdir/tensorprimitives-rs` with no version suffix, while the TAPP_LOCAL_SRC
# export is prefixed `tensorprimitives-rs-0.1.0`. Only one ever exists.
cd ${WORKSPACE}/srcdir/tensorprimitives-rs*/

# RUSTFLAGS is assembled rather than assigned: two of the three fragments are
# conditional, and cargo reads the variable whole or not at all.
RFLAGS=()

# musl defaults to `crt-static`, and a cdylib cannot be produced with it on.
# Without this flag cargo prints "dropping unsupported crate type `cdylib`" and
# *exits 0*, so the build succeeds and the tarball contains a header and no
# library. See rust-lang/rust#59302 and rust-lang/cargo#8607.
if [[ "${target}" == *-musl* ]]; then
    RFLAGS+=(-C target-feature=-crt-static)
fi

# rustc emits `-soname` only for the `dylib` crate type, never for `cdylib`, so
# the ELF would otherwise carry no DT_SONAME and every consumer would record a
# bare filename. On Mach-O the problem is worse than absent: ld64 defaults
# LC_ID_DYLIB to the `-o` path, i.e. an absolute build-tree path, and the
# auditor's `ensure_soname` autofix returns early whenever an ID is merely
# *present* -- it does not inspect the value -- so the library would ship
# unrelocatable and the audit would pass in silence.
#
# Set at link time rather than with patchelf/install_name_tool afterwards: one
# mechanism for both platforms, and no ELF rewriting, which on the 64 KiB-page
# architectures (aarch64, ppc64le, riscv64) needs `patchelf --page-size 65536`
# or it corrupts section alignment. Do NOT reach for `-C rpath` for the macOS
# half: it does set the install name, and also bakes build-tree LC_RPATH entries
# into the library.
if [[ "${target}" == *-apple-* ]]; then
    RFLAGS+=(-C link-arg=-Wl,-install_name,@rpath/libtensorprimitives_tapp.${dlext})
elif [[ "${target}" != *-mingw* ]]; then
    RFLAGS+=(-C link-arg=-Wl,-soname,libtensorprimitives_tapp.${dlext})
fi

export RUSTFLAGS="${RFLAGS[@]}"

# The workspace release profile sets `debug = 1` for profiling on the reference
# machine. A distributed binary ships no debug info.
export CARGO_PROFILE_RELEASE_DEBUG=0

# `-p tensorprimitives-tapp` is load-bearing, not tidiness: `tensorprimitives-bench`
# is a workspace member whose build script requires TBLIS_ROOT and must never be
# built here. Selecting one package resolves the whole workspace but runs no other
# member's build script.
#
# `--locked` needs the committed Cargo.lock. It is what makes this artifact
# reproducible -- without it a num-traits patch release silently changes what a
# user downloads relative to what was tested -- and it turns an absent or stale
# lockfile into a loud error at the top of the build.
#
# `--target ${rust_target}` is redundant (BinaryBuilder exports
# CARGO_BUILD_TARGET) but makes the artifact paths below self-evident.
cargo build --release --locked -j${nproc} --target ${rust_target} -p tensorprimitives-tapp

# One definition of the installed layout, shared with every non-BinaryBuilder
# install: the script writes lib/, include/, lib/pkgconfig/ and share/licenses/,
# and `examples/c-consumer`'s TAPP_PREFIX mode consumes exactly that, so the
# layout is tested in the repository's own CI rather than only here.
#
# It finds the library by filename, which is what makes it correct under
# cross-compilation: on `*-mingw*` rustc's target spec sets an empty dll_prefix,
# so the artifact is `tensorprimitives_tapp.dll` with no `lib`, and ${libdir} is
# ${prefix}/bin rather than ${prefix}/lib.
crates/tensorprimitives-tapp/install.sh \
    --prefix="${prefix}" \
    --libdir="${libdir}" \
    --includedir="${includedir}" \
    --artifacts="target/${rust_target}/release" \
    --no-licenses

# `--no-licenses` above, and the conventional helper here, because the two
# disagree about the directory name and the auditor sides with the helper: it
# looks under share/licenses/${package_name}, i.e. `tensorprimitives_tapp` with an
# underscore, while install.sh uses the crate name `tensorprimitives-tapp` with a
# hyphen. Installing both would ship two copies of each licence under two names;
# installing only install.sh's produced "Unable to find valid license file in
# ${prefix}/share/licenses/tensorprimitives_tapp" from the auditor, which is one
# of the two things a Yggdrasil reviewer greps the log for.
install_license LICENSE-MIT LICENSE-APACHE
"""

platforms = supported_platforms()

# BinaryBuilder's own build tips document its Rust toolchain as unusable for
# 32-bit Windows, and every Rust recipe in Yggdrasil carries this filter. The
# shard exists, so without this the build is attempted and fails at link.
filter!(p -> !Sys.iswindows(p) || arch(p) != "i686", platforms)

# `riscv64-linux-gnu` and `aarch64-unknown-freebsd` have **no Rust toolchain
# shard at any available version**. Checked rather than assumed, against the
# BinaryBuilderBase that BinaryBuilder 0.6.6 actually resolves to:
#
#   for p in supported_platforms()
#       choose_shards(p; preferred_rust_version=v"1.94.0", compilers=[:c, :rust])
#   end
#
# fails for exactly these two and succeeds for the other 16. Both would take the
# scalar path anyway, so neither is a loss worth chasing; drop the filter if a
# later toolchain gains them.
filter!(p -> !(triplet(p) in ("riscv64-linux-gnu", "aarch64-unknown-freebsd")), platforms)

products = [
    # Two candidate names. On `*-mingw*` the cdylib is `tensorprimitives_tapp.dll`
    # -- rustc's windows_gnu target base sets `dll_prefix = ""` -- and renaming it
    # to gain the `lib` would desynchronise it from its own import library, which
    # records the DLL name internally. Listing both names is the cheaper fix.
    LibraryProduct(
        ["libtensorprimitives_tapp", "tensorprimitives_tapp"],
        :libtensorprimitives_tapp,
    ),
    # The header is half of what this package is for: the whole point of D36 is
    # that a C or C++ consumer gets declarations that version with the
    # implementation. As a product, a missing header is an audit failure rather
    # than a downstream one.
    FileProduct("include/tapp.h", :tapp_h),
]

# Nothing. The engine is native Rust with two pure-Rust dependency crates
# (num-complex, num-traits) and no build script, so there is no system library to
# resolve: no BLAS, no MPI, no C++ runtime. Keeping this empty is worth defending.
#
# The audit will nonetheless warn
#
#   lib/libtensorprimitives_tapp.so: Linked library libgcc_s.so.1 could not be
#   resolved and could not be auto-mapped
#
# and that warning is expected. Every Rust cdylib carries a DT_NEEDED on
# `libgcc_s.so.1` for its unwinder, and Julia ships one in its own private libdir,
# so it resolves at run time in the only process that will ever load this. This was
# not taken on faith: `CompilerSupportLibraries_jll` was tried here and made things
# worse rather than better -- it adds "does not have a mapping for artifact
# CompilerSupportLibraries for platform x86_64-linux-gnu-libgfortran3-cxx11",
# because CSL's artifacts are keyed by libgfortran version and this package has no
# reason to expand its platforms over them, *and* it does not silence the original
# warning. `check_csl_libs` agrees: it flags `libgomp` and `libatomic`, not
# `libgcc_s`. If a reviewer asks, this paragraph is the answer.
#
# On Windows the equivalent warning names `bcryptprimitives.dll`, which is a
# Windows 10+ system DLL that Rust's standard library imports for randomness and
# that the auditor's system-library list does not know about. Same situation, same
# answer: it is present wherever the DLL can run, and there is no JLL to point at.
#
# These are the only two unresolved-library warnings this build produces. A *third*
# one would be a real finding.
dependencies = Dependency[]

build_tarballs(
    ARGS, name, version, sources, script, platforms, products, dependencies;
    # Pinned so the toolchain cannot move underneath a rebuild. 1.94.0 is the
    # newest shard the released BinaryBuilder offers -- `available_rust_builds`
    # runs 1.57.0 to 1.94.0 -- and it is comfortably above the crate's 1.89 MSRV.
    # Do not raise this to a version read from BinaryBuilderBase's master branch:
    # `choose_shards` *errors* on a version that has no shard, so an optimistic
    # pin is a hard build failure rather than a graceful fallback.
    preferred_rust_version = v"1.94.0",
    compilers = [:c, :rust],
    # `:c` is not optional: it supplies the `cc` that BinaryBuilder names as
    # cargo's linker in the config.toml it generates.
    julia_compat = "1.6",
)
