#ifndef CIMGUI_HELPER
#define CIMGUI_HELPER

#define CIMGUI_DEFINE_ENUMS_AND_STRUCTS
#include "cimgui.h"

// ImGuiIO_Get
CIMGUI_API ImGuiConfigFlags ImGuiIO_Get_ConfigFlags(ImGuiIO* io);
CIMGUI_API ImGuiBackendFlags ImGuiIO_Get_BackendFlags(ImGuiIO* io);
CIMGUI_API ImVec2 ImGuiIO_Get_DisplaySize(ImGuiIO* io);
CIMGUI_API float ImGuiIO_Get_DeltaTime(ImGuiIO* io);
CIMGUI_API float ImGuiIO_Get_IniSavingRate(ImGuiIO* io);
CIMGUI_API const char* ImGuiIO_Get_IniFilename(ImGuiIO* io);
CIMGUI_API const char* ImGuiIO_Get_LogFilename(ImGuiIO* io);
CIMGUI_API float ImGuiIO_Get_MouseDoubleClickTime(ImGuiIO* io);
CIMGUI_API float ImGuiIO_Get_MouseDoubleClickMaxDist(ImGuiIO* io);
CIMGUI_API float ImGuiIO_Get_MouseDragThreshold(ImGuiIO* io);
CIMGUI_API int ImGuiIO_Get_KeyMap(ImGuiIO* io, int i);
CIMGUI_API float ImGuiIO_Get_KeyRepeatDelay(ImGuiIO* io);
CIMGUI_API float ImGuiIO_Get_KeyRepeatRate(ImGuiIO* io);
CIMGUI_API void* ImGuiIO_Get_UserData(ImGuiIO* io);
CIMGUI_API ImFontAtlas* ImGuiIO_Get_Fonts(ImGuiIO* io);
CIMGUI_API float ImGuiIO_Get_FontGlobalScale(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_FontAllowUserScaling(ImGuiIO* io);
CIMGUI_API ImFont* ImGuiIO_Get_FontDefault(ImGuiIO* io);
CIMGUI_API ImVec2 ImGuiIO_Get_DisplayFramebufferScale(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_MouseDrawCursor(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_ConfigMacOSXBehaviors(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_ConfigInputTextCursorBlink(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_ConfigWindowsResizeFromEdges(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_ConfigWindowsMoveFromTitleBarOnly(ImGuiIO* io);
CIMGUI_API const char* ImGuiIO_Get_BackendPlatformName(ImGuiIO* io);
CIMGUI_API const char* ImGuiIO_Get_BackendRendererName(ImGuiIO* io);
CIMGUI_API void* ImGuiIO_Get_BackendPlatformUserData(ImGuiIO* io);
CIMGUI_API void* ImGuiIO_Get_BackendRendererUserData(ImGuiIO* io);
CIMGUI_API void* ImGuiIO_Get_BackendLanguageUserData(ImGuiIO* io);
CIMGUI_API void* ImGuiIO_Get_ImeWindowHandle(ImGuiIO* io);
CIMGUI_API void* ImGuiIO_Get_RenderDrawListsFnUnused(ImGuiIO* io);
CIMGUI_API ImVec2 ImGuiIO_Get_MousePos(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_MouseDown(ImGuiIO* io, int i);
CIMGUI_API float ImGuiIO_Get_MouseWheel(ImGuiIO* io);
CIMGUI_API float ImGuiIO_Get_MouseWheelH(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_KeyCtrl(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_KeyShift(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_KeyAlt(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_KeySuper(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_KeysDown(ImGuiIO* io, int i);
CIMGUI_API float ImGuiIO_Get_NavInputs(ImGuiIO* io, int i);
CIMGUI_API bool ImGuiIO_Get_WantCaptureMouse(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_WantCaptureKeyboard(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_WantTextInput(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_WantSetMousePos(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_WantSaveIniSettings(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_NavActive(ImGuiIO* io);
CIMGUI_API bool ImGuiIO_Get_NavVisible(ImGuiIO* io);
CIMGUI_API float ImGuiIO_Get_Framerate(ImGuiIO* io);
CIMGUI_API int ImGuiIO_Get_MetricsRenderVertices(ImGuiIO* io);
CIMGUI_API int ImGuiIO_Get_MetricsRenderIndices(ImGuiIO* io);
CIMGUI_API int ImGuiIO_Get_MetricsRenderWindows(ImGuiIO* io);
CIMGUI_API int ImGuiIO_Get_MetricsActiveWindows(ImGuiIO* io);
CIMGUI_API int ImGuiIO_Get_MetricsActiveAllocations(ImGuiIO* io);
CIMGUI_API ImVec2 ImGuiIO_Get_MouseDelta(ImGuiIO* io);
CIMGUI_API ImVec2 ImGuiIO_Get_MousePosPrev(ImGuiIO* io);
CIMGUI_API ImVec2 ImGuiIO_Get_MouseClickedPos(ImGuiIO* io, int i);
CIMGUI_API double ImGuiIO_Get_MouseClickedTime(ImGuiIO* io, int i);
CIMGUI_API bool ImGuiIO_Get_MouseClicked(ImGuiIO* io, int i);
CIMGUI_API bool ImGuiIO_Get_MouseDoubleClicked(ImGuiIO* io, int i);
CIMGUI_API bool ImGuiIO_Get_MouseReleased(ImGuiIO* io, int i);
CIMGUI_API bool ImGuiIO_Get_MouseDownOwned(ImGuiIO* io, int i);
CIMGUI_API float ImGuiIO_Get_MouseDownDuration(ImGuiIO* io, int i);
CIMGUI_API float ImGuiIO_Get_MouseDownDurationPrev(ImGuiIO* io, int i);
CIMGUI_API ImVec2 ImGuiIO_Get_MouseDragMaxDistanceAbs(ImGuiIO* io, int i);
CIMGUI_API float ImGuiIO_Get_MouseDragMaxDistanceSqr(ImGuiIO* io, int i);
CIMGUI_API float ImGuiIO_Get_KeysDownDuration(ImGuiIO* io, int i);
CIMGUI_API float ImGuiIO_Get_KeysDownDurationPrev(ImGuiIO* io, int i);
CIMGUI_API float ImGuiIO_Get_NavInputsDownDuration(ImGuiIO* io, int i);
CIMGUI_API float ImGuiIO_Get_NavInputsDownDurationPrev(ImGuiIO* io, int i);
CIMGUI_API ImVector_ImWchar ImGuiIO_Get_InputQueueCharacters(ImGuiIO* io) ;
// ImGuiIO_Set
CIMGUI_API void ImGuiIO_Set_ConfigFlags(ImGuiIO* io, ImGuiConfigFlags x);
CIMGUI_API void ImGuiIO_Set_BackendFlags(ImGuiIO* io, ImGuiBackendFlags x);
CIMGUI_API void ImGuiIO_Set_DisplaySize(ImGuiIO* io, ImVec2 x);
CIMGUI_API void ImGuiIO_Set_DeltaTime(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_IniSavingRate(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_IniFilename(ImGuiIO* io, const char* x);
CIMGUI_API void ImGuiIO_Set_LogFilename(ImGuiIO* io, const char* x);
CIMGUI_API void ImGuiIO_Set_MouseDoubleClickTime(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_MouseDoubleClickMaxDist(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_MouseDragThreshold(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_KeyMap(ImGuiIO* io, int i, int x);
CIMGUI_API void ImGuiIO_Set_KeyRepeatDelay(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_KeyRepeatRate(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_UserData(ImGuiIO* io, void* x);
CIMGUI_API void ImGuiIO_Set_Fonts(ImGuiIO* io, ImFontAtlas* x);
CIMGUI_API void ImGuiIO_Set_FontGlobalScale(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_FontAllowUserScaling(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_FontDefault(ImGuiIO* io, ImFont* x);
CIMGUI_API void ImGuiIO_Set_DisplayFramebufferScale(ImGuiIO* io, ImVec2 x);
CIMGUI_API void ImGuiIO_Set_MouseDrawCursor(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_ConfigMacOSXBehaviors(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_ConfigInputTextCursorBlink(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_ConfigWindowsResizeFromEdges(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_ConfigWindowsMoveFromTitleBarOnly(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_BackendPlatformName(ImGuiIO* io, const char* x);
CIMGUI_API void ImGuiIO_Set_BackendRendererName(ImGuiIO* io, const char* x);
CIMGUI_API void ImGuiIO_Set_BackendPlatformUserData(ImGuiIO* io, void* x);
CIMGUI_API void ImGuiIO_Set_BackendRendererUserData(ImGuiIO* io, void* x);
CIMGUI_API void ImGuiIO_Set_BackendLanguageUserData(ImGuiIO* io, void* x);
CIMGUI_API void ImGuiIO_Set_GetClipboardTextFn(ImGuiIO* io, void* x);
CIMGUI_API void ImGuiIO_Set_SetClipboardTextFn(ImGuiIO* io, void* x);
CIMGUI_API void ImGuiIO_Set_ClipboardUserData(ImGuiIO* io, void* x);
CIMGUI_API void ImGuiIO_Set_ImeSetInputScreenPosFn(ImGuiIO* io, void* x);
CIMGUI_API void ImGuiIO_Set_ImeWindowHandle(ImGuiIO* io, void* x);
CIMGUI_API void ImGuiIO_Set_RenderDrawListsFnUnused(ImGuiIO* io, void* x);
CIMGUI_API void ImGuiIO_Set_MousePos(ImGuiIO* io, ImVec2 x);
CIMGUI_API void ImGuiIO_Set_MouseDown(ImGuiIO* io, int i, bool x);
CIMGUI_API void ImGuiIO_Set_MouseWheel(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_MouseWheelH(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_KeyCtrl(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_KeyShift(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_KeyAlt(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_KeySuper(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_KeysDown(ImGuiIO* io, int i, bool x);
CIMGUI_API void ImGuiIO_Set_NavInputs(ImGuiIO* io, int i, float x);
CIMGUI_API void ImGuiIO_Set_WantCaptureMouse(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_WantCaptureKeyboard(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_WantTextInput(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_WantSetMousePos(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_WantSaveIniSettings(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_NavActive(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_NavVisible(ImGuiIO* io, bool x);
CIMGUI_API void ImGuiIO_Set_Framerate(ImGuiIO* io, float x);
CIMGUI_API void ImGuiIO_Set_MetricsRenderVertices(ImGuiIO* io, int x) ;
CIMGUI_API void ImGuiIO_Set_MetricsRenderIndices(ImGuiIO* io, int x);
CIMGUI_API void ImGuiIO_Set_MetricsRenderWindows(ImGuiIO* io, int x);
CIMGUI_API void ImGuiIO_Set_MetricsActiveWindows(ImGuiIO* io, int x);
CIMGUI_API void ImGuiIO_Set_MetricsActiveAllocations(ImGuiIO* io, int x);
CIMGUI_API void ImGuiIO_Set_MouseDelta(ImGuiIO* io, ImVec2 x);
CIMGUI_API void ImGuiIO_Set_MousePosPrev(ImGuiIO* io, ImVec2 x);
CIMGUI_API void ImGuiIO_Set_MouseClickedPos(ImGuiIO* io, int i, ImVec2 x);
CIMGUI_API void ImGuiIO_Set_MouseClickedTime(ImGuiIO* io, int i, double x);
CIMGUI_API void ImGuiIO_Set_MouseClicked(ImGuiIO* io, int i, bool x);
CIMGUI_API void ImGuiIO_Set_MouseDoubleClicked(ImGuiIO* io, int i, bool x);
CIMGUI_API void ImGuiIO_Set_MouseReleased(ImGuiIO* io, int i, bool x);
CIMGUI_API void ImGuiIO_Set_MouseDownOwned(ImGuiIO* io, int i, bool x);
CIMGUI_API void ImGuiIO_Set_MouseDownDuration(ImGuiIO* io, int i, float x);
CIMGUI_API void ImGuiIO_Set_MouseDownDurationPrev(ImGuiIO* io, int i, float x);
CIMGUI_API void ImGuiIO_Set_MouseDragMaxDistanceAbs(ImGuiIO* io, int i, ImVec2 x);
CIMGUI_API void ImGuiIO_Set_MouseDragMaxDistanceSqr(ImGuiIO* io, int i, float x);
CIMGUI_API void ImGuiIO_Set_KeysDownDuration(ImGuiIO* io, int i, float x);
CIMGUI_API void ImGuiIO_Set_KeysDownDurationPrev(ImGuiIO* io, int i, float x);
CIMGUI_API void ImGuiIO_Set_NavInputsDownDuration(ImGuiIO* io, int i, float x);
CIMGUI_API void ImGuiIO_Set_NavInputsDownDurationPrev(ImGuiIO* io, int i, float x);

// ImGuiStyle_Get
CIMGUI_API float ImGuiStyle_Get_Alpha(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_WindowPadding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_WindowRounding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_WindowBorderSize(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_WindowMinSize(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_WindowTitleAlign(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_ChildRounding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_ChildBorderSize(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_PopupRounding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_PopupBorderSize(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_FramePadding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_FrameRounding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_FrameBorderSize(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_ItemSpacing(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_ItemInnerSpacing(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_TouchExtraPadding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_IndentSpacing(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_ColumnsMinSpacing(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_ScrollbarSize(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_ScrollbarRounding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_GrabMinSize(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_GrabRounding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_TabRounding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_TabBorderSize(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_ButtonTextAlign(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_SelectableTextAlign(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_DisplayWindowPadding(ImGuiStyle* s);
CIMGUI_API ImVec2 ImGuiStyle_Get_DisplaySafeAreaPadding(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_MouseCursorScale(ImGuiStyle* s);
CIMGUI_API bool ImGuiStyle_Get_AntiAliasedLines(ImGuiStyle* s);
CIMGUI_API bool ImGuiStyle_Get_AntiAliasedFill(ImGuiStyle* s);
CIMGUI_API float ImGuiStyle_Get_CurveTessellationTol(ImGuiStyle* s);
CIMGUI_API ImVec4 ImGuiStyle_Get_Colors(ImGuiStyle* s, int i);

// ImGuiStyle_Set
CIMGUI_API void ImGuiStyle_Set_Alpha(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_WindowPadding(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_WindowRounding(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_WindowBorderSize(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_WindowMinSize(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_WindowTitleAlign(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_ChildRounding(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_ChildBorderSize(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_PopupRounding(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_PopupBorderSize(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_FramePadding(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_FrameRounding(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_FrameBorderSize(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_ItemSpacing(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_ItemInnerSpacing(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_TouchExtraPadding(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_IndentSpacing(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_ColumnsMinSpacing(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_ScrollbarSize(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_ScrollbarRounding(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_GrabMinSize(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_GrabRounding(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_TabRounding(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_TabBorderSize(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_ButtonTextAlign(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_SelectableTextAlign(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_DisplayWindowPadding(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_DisplaySafeAreaPadding(ImGuiStyle* s, ImVec2 v);
CIMGUI_API void ImGuiStyle_Set_MouseCursorScale(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_AntiAliasedLines(ImGuiStyle* s, bool v);
CIMGUI_API void ImGuiStyle_Set_AntiAliasedFill(ImGuiStyle* s, bool v);
CIMGUI_API void ImGuiStyle_Set_CurveTessellationTol(ImGuiStyle* s, float v);
CIMGUI_API void ImGuiStyle_Set_Colors(ImGuiStyle* s, int i, ImVec4 v);

// ImDrawData_Get
CIMGUI_API bool ImDrawData_Get_Valid(ImDrawData* data);
CIMGUI_API ImDrawList* ImDrawData_Get_CmdLists(ImDrawData* data, int i);
CIMGUI_API int ImDrawData_Get_CmdListsCount(ImDrawData* data);
CIMGUI_API int ImDrawData_Get_TotalIdxCount(ImDrawData* data);
CIMGUI_API int ImDrawData_Get_TotalVtxCount(ImDrawData* data);
CIMGUI_API ImVec2 ImDrawData_Get_DisplayPos(ImDrawData* data);
CIMGUI_API ImVec2 ImDrawData_Get_DisplaySize(ImDrawData* data);
CIMGUI_API ImVec2 ImDrawData_Get_FramebufferScale(ImDrawData* data);

// ImDrawList_Get
CIMGUI_API ImVector_ImDrawCmd ImDrawList_Get_CmdBuffer(ImDrawList* list);
CIMGUI_API ImVector_ImDrawIdx ImDrawList_Get_IdxBuffer(ImDrawList* list);
CIMGUI_API ImVector_ImDrawVert ImDrawList_Get_VtxBuffer(ImDrawList* list);

// ImDrawCmd_Get
CIMGUI_API unsigned int ImDrawCmd_Get_ElemCount(ImDrawCmd* cmd);
CIMGUI_API ImVec4 ImDrawCmd_Get_ClipRect(ImDrawCmd* cmd);
CIMGUI_API ImTextureID ImDrawCmd_Get_TextureId(ImDrawCmd* cmd);
CIMGUI_API unsigned int ImDrawCmd_Get_VtxOffset(ImDrawCmd* cmd);
CIMGUI_API unsigned int ImDrawCmd_Get_IdxOffset(ImDrawCmd* cmd);
CIMGUI_API ImDrawCallback ImDrawCmd_Get_UserCallback(ImDrawCmd* cmd);
CIMGUI_API void* ImDrawCmd_Get_UserCallbackData(ImDrawCmd* cmd);

// ImGuiSizeCallbackData_Get
CIMGUI_API void* ImGuiSizeCallbackData_Get_UserData(ImGuiSizeCallbackData* data);
CIMGUI_API ImVec2 ImGuiSizeCallbackData_Get_Pos(ImGuiSizeCallbackData* data);
CIMGUI_API ImVec2 ImGuiSizeCallbackData_Get_CurrentSize(ImGuiSizeCallbackData* data);
CIMGUI_API ImVec2 ImGuiSizeCallbackData_Get_DesiredSize(ImGuiSizeCallbackData* data);
// ImGuiSizeCallbackData_Set
CIMGUI_API void ImGuiSizeCallbackData_Set_DesiredSize(ImGuiSizeCallbackData* data, ImVec2 x);

// ImFontAtlas_Get
CIMGUI_API bool ImFontAtlas_Get_Locked(ImFontAtlas* f);
CIMGUI_API ImFontAtlasFlags ImFontAtlas_Get_Flags(ImFontAtlas* f);
CIMGUI_API ImTextureID ImFontAtlas_Get_TexID(ImFontAtlas* f);
CIMGUI_API int ImFontAtlas_Get_TexDesiredWidth(ImFontAtlas* f);
CIMGUI_API int ImFontAtlas_Get_TexGlyphPadding(ImFontAtlas* f);
CIMGUI_API unsigned char* ImFontAtlas_Get_TexPixelsAlpha8(ImFontAtlas* f);
CIMGUI_API unsigned int* ImFontAtlas_Get_TexPixelsRGBA32(ImFontAtlas* f);
CIMGUI_API int ImFontAtlas_Get_TexWidth(ImFontAtlas* f);
CIMGUI_API int ImFontAtlas_Get_TexHeight(ImFontAtlas* f);
CIMGUI_API ImVec2 ImFontAtlas_Get_TexUvScale(ImFontAtlas* f);
CIMGUI_API ImVec2 ImFontAtlas_Get_TexUvWhitePixel(ImFontAtlas* f);

#endif // CIMGUI_HELPER
