# The purpose of this file is to control which reviewers are assigned as part of
# the `.github/workflows/component_owners.yml` workflow.
#
# See https://github.com/dyladan/component-owners for the file format.
#
# Please keep the list of components and reviewers in alphabetical order.
components:
  B/basiclu/:
    - amontoison
  C/ColPack/:
    - amontoison
  C/Coin-OR/:
    - odow
  C/Coin-OR/Ipopt/:
    - amontoison
  C/CUTEst/:
    - amontoison
  C/CUDA/CUDSS/:
    - amontoison
  G/GALAHAD/:
    - amontoison
  G/GLPK/:
    - odow
  H/HiGHS/:
    - odow
  H/HSL/:
    - amontoison
  I/IntelOpenMP/:
    - amontoison
  I/ipx/:
    - amontoison
  L/LAPACK/:
    - amontoison
  L/libblastrampoline/:
    - amontoison
  M/METIS/:
    - amontoison
  M/MKL/:
    - amontoison
  M/MKL_Headers/:
    - amontoison
  M/MUMPS/:
    - amontoison
  N/NOMAD/:
    - amontoison
  O/oneAPI_support/:
    - amontoison
  O/oneAPI_support_Headers/:
    - amontoison
  P/PARMETIS/:
    - amontoison
  P/PaStiX/:
    - amontoison
  P/PRIMA/:
    - amontoison
  P/ProxTV/:
    - amontoison
  P/PROPACK/:
    - amontoison
  P/PTSCOTCH/:
    - amontoison
  Q/qr_mumps/:
    - amontoison
  R/ReferenceBLAS/:
    - amontoison
  S/SCALAPACK/:
    - amontoison
  S/SCALAPACK32/:
    - amontoison
  S/SCIP/:
    - odow
  S/SCIP_PaPILO/:
    - odow
  S/SCS/:
    - kalmarek
    - odow
  S/SCOTCH/:
    - amontoison
  S/SCS_GPU/:
    - kalmarek
    - odow
  S/SCS_MKL/:
    - kalmarek
    - odow
  S/SDPA/:
    - blegat
    - odow
  S/SIFDecode/:
    - amontoison
  S/SOLAR/:
    - amontoison
  S/SPRAL/:
    - amontoison
  S/StarPU/:
    - amontoison
  S/STYRENE/:
    - amontoison
  U/Uno/:
    - amontoison
