# The purpose of this file is to control which reviewers are assigned as part of
# the `.github/workflows/component_owners.yml` workflow.
#
# See https://github.com/dyladan/component-owners for the file format.
#
# Please keep the list of components and reviewers in alphabetical order.
#
# Note that users MUST be collaborators on the JuliaPackaging/Yggdrasil
# repository, but they do not need write access.
components:
  C/Coin-OR/:
    - odow
  G/GLPK/:
    - odow
  H/HiGHS/:
    - odow
  S/SCIP/:
    - odow
  S/SCIP_PaPILO/:
    - odow
  S/SCS/:
    - odow
  S/SCS_GPU/:
    - odow
  S/SCS_MKL/:
    - odow
  S/SDPA/:
    - odow
