# Note that this script can accept some limited command-line arguments, run
# `julia build_tarballs.jl --help` to see a usage message.
using BinaryBuilder, Pkg

name = "OpenFOAM"
version = v"8.0"

# Collection of sources required to complete build
sources = [
    ArchiveSource("https://github.com/OpenFOAM/OpenFOAM-8/archive/version-8.tar.gz",
                  "94ba11cbaaa12fbb5b356e01758df403ac8832d69da309a5d79f76f42eb008fc"),
    DirectorySource("./bundled"),
]

# In order to set up OpenFOAM, we need to know the version of some of the
# dependencies.
const SCOTCH_VERSION = "6.1.0"

# Bash recipe for building across all platforms
script = "SCOTCH_VERSION=$(SCOTCH_VERSION)\n" * raw"""
cd ${WORKSPACE}/srcdir/OpenFOAM*
atomic_patch -p1 ../patches/etc-bashrc.patch

# Set rpath-link in all C/C++ compilers
LDFLAGS=""
for dir in "" "/dummy" "/mpi-system"; do
    LDFLAGS="${LDFLAGS} -Wl,-rpath-link=${PWD}/platforms/linux64GccDPInt32Opt/lib${dir}"
done
sed -i "s?-m64?-m64 ${LDFLAGS}?g" wmake/rules/*/c*

# Set version of Scotch
echo "export SCOTCH_VERSION=${SCOTCH_VERSION}" > etc/config.sh/scotch
echo "export SCOTCH_ARCH_PATH=${prefix}"      >> etc/config.sh/scotch

# Set up to use our MPI (MPICH)
sed -i 's/WM_MPLIB=SYSTEMOPENMPI/WM_MPLIB=SYSTEMMPI/g' etc/bashrc
export MPI_ROOT="${prefix}"
export MPI_ARCH_FLAGS=""
export MPI_ARCH_INC="-I${includedir}"
export MPI_ARCH_LIBS="-L${libdir} -lmpi"

# Set up the environment.  Note, this script may internally have some failing command, which
# would spring our traps, so we have to allow failures, sigh
source etc/bashrc || true

# Build!
./Allwmake -j${nproc}

# Highly advanced installation process (inspired by Debian:
# https://salsa.debian.org/science-team/openfoam/-/tree/master/debian)
mkdir -p ${libdir} ${bindir}
cp platforms/linux64GccDPInt32Opt/bin/* "${bindir}/."
cp platforms/linux64GccDPInt32Opt/lib/{,dummy/,mpi-system/}*.${dlext}* "${libdir}/."
"""

# These are the platforms we will build for by default, unless further
# platforms are passed in on the command line
platforms = [
    Platform("x86_64", "linux"; libc="glibc"),
]
platforms = expand_cxxstring_abis(platforms)

# The products that we will ensure are always built
products = [
    LibraryProduct("libatmosphericModels", :libatmosphericModels),
    LibraryProduct("libbarotropicCompressibilityModel", :libbarotropicCompressibilityModel),
    LibraryProduct("libblockMesh", :libblockMesh),
    LibraryProduct("libchemistryModel", :libchemistryModel),
    LibraryProduct("libcoalCombustion", :libcoalCombustion),
    LibraryProduct("libcombustionModels", :libcombustionModels),
    LibraryProduct("libconversion", :libconversion),
    LibraryProduct("libdecompose", :libdecompose),
    LibraryProduct("libdecompositionMethods", :libdecompositionMethods),
    LibraryProduct("libdistributed", :libdistributed),
    LibraryProduct("libdistributionModels", :libdistributionModels),
    LibraryProduct("libDPMMomentumTransportModels", :libDPMMomentumTransportModels),
    LibraryProduct("libdriftFluxRelativeVelocityModels", :libdriftFluxRelativeVelocityModels),
    LibraryProduct("libdriftFluxTransportModels", :libdriftFluxTransportModels),
    LibraryProduct("libDSMC", :libDSMC),
    LibraryProduct("libdynamicFvMesh", :libdynamicFvMesh),
    LibraryProduct("libdynamicMesh", :libdynamicMesh),
    LibraryProduct("libengine", :libengine),
    LibraryProduct("libeulerianInterfacialCompositionModels", :libeulerianInterfacialCompositionModels),
    LibraryProduct("libeulerianInterfacialModels", :libeulerianInterfacialModels),
    LibraryProduct("libextrude2DMesh", :libextrude2DMesh),
    LibraryProduct("libextrudeModel", :libextrudeModel),
    LibraryProduct("libfieldFunctionObjects", :libfieldFunctionObjects),
    LibraryProduct("libfileFormats", :libfileFormats),
    LibraryProduct("libfiniteVolume", :libfiniteVolume),
    LibraryProduct("libfluidThermoMomentumTransportModels", :libfluidThermoMomentumTransportModels),
    LibraryProduct("libfluidThermophysicalModels", :libfluidThermophysicalModels),
    LibraryProduct("libfoamToVTK", :libfoamToVTK),
    LibraryProduct("libforces", :libforces),
    LibraryProduct("libfvMotionSolvers", :libfvMotionSolvers),
    LibraryProduct("libfvOptions", :libfvOptions),
    LibraryProduct("libgenericPatchFields", :libgenericPatchFields),
    LibraryProduct("libimmiscibleIncompressibleTwoPhaseMixture", :libimmiscibleIncompressibleTwoPhaseMixture),
    LibraryProduct("libincompressibleMomentumTransportModels", :libincompressibleMomentumTransportModels),
    LibraryProduct("libincompressibleTransportModels", :libincompressibleTransportModels),
    LibraryProduct("libincompressibleTwoPhaseMixture", :libincompressibleTwoPhaseMixture),
    LibraryProduct("libinterfaceProperties", :libinterfaceProperties),
    LibraryProduct("liblagrangianFunctionObjects", :liblagrangianFunctionObjects),
    LibraryProduct("liblagrangianIntermediate", :liblagrangianIntermediate),
    LibraryProduct("liblagrangian", :liblagrangian),
    LibraryProduct("liblagrangianSpray", :liblagrangianSpray),
    LibraryProduct("liblagrangianTurbulence", :liblagrangianTurbulence),
    LibraryProduct("liblaminarFlameSpeedModels", :liblaminarFlameSpeedModels),
    LibraryProduct("libmeshTools", :libmeshTools),
    LibraryProduct("libmetisDecomp", :libmetisDecomp),
    LibraryProduct("libMGridGen", :libMGridGen),
    LibraryProduct("libmolecularMeasurements", :libmolecularMeasurements),
    LibraryProduct("libmolecule", :libmolecule),
    LibraryProduct("libmomentumTransportModels", :libmomentumTransportModels),
    LibraryProduct("libmultiphaseEulerFoamFunctionObjects", :libmultiphaseEulerFoamFunctionObjects),
    LibraryProduct("libmultiphaseInterFoam", :libmultiphaseInterFoam),
    LibraryProduct("libmultiphaseMixtureThermo", :libmultiphaseMixtureThermo),
    LibraryProduct("libmultiphaseMomentumTransportModels", :libmultiphaseMomentumTransportModels),
    LibraryProduct("libmultiphaseSystems", :libmultiphaseSystems),
    LibraryProduct("libmultiphaseThermophysicalTransportModels", :libmultiphaseThermophysicalTransportModels),
    LibraryProduct("libODE", :libODE),
    LibraryProduct("libOpenFOAM", :libOpenFOAM),
    LibraryProduct("libpairPatchAgglomeration", :libpairPatchAgglomeration),
    LibraryProduct("libphaseChangeTwoPhaseMixtures", :libphaseChangeTwoPhaseMixtures),
    LibraryProduct("libphaseSystem", :libphaseSystem),
    LibraryProduct("libpotential", :libpotential),
    LibraryProduct("libpsiReactionThermophysicalTransportModels", :libpsiReactionThermophysicalTransportModels),
    LibraryProduct("libPstream", :libPstream),
    LibraryProduct("libptscotchDecomp", :libptscotchDecomp),
    LibraryProduct("libradiationModels", :libradiationModels),
    LibraryProduct("librandomProcesses", :librandomProcesses),
    LibraryProduct("libreactionThermophysicalModels", :libreactionThermophysicalModels),
    LibraryProduct("libreconstruct", :libreconstruct),
    LibraryProduct("libregionModels", :libregionModels),
    LibraryProduct("librenumberMethods", :librenumberMethods),
    LibraryProduct("librhoCentralFoam", :librhoCentralFoam),
    LibraryProduct("librhoReactionThermophysicalTransportModels", :librhoReactionThermophysicalTransportModels),
    LibraryProduct("librigidBodyDynamics", :librigidBodyDynamics),
    LibraryProduct("librigidBodyMeshMotion", :librigidBodyMeshMotion),
    LibraryProduct("librigidBodyState", :librigidBodyState),
    LibraryProduct("libsampling", :libsampling),
    LibraryProduct("libscotchDecomp", :libscotchDecomp),
    LibraryProduct("libsixDoFRigidBodyMotion", :libsixDoFRigidBodyMotion),
    LibraryProduct("libsixDoFRigidBodyState", :libsixDoFRigidBodyState),
    LibraryProduct("libSLGThermo", :libSLGThermo),
    LibraryProduct("libsnappyHexMesh", :libsnappyHexMesh),
    LibraryProduct("libsolidDisplacementThermo", :libsolidDisplacementThermo),
    LibraryProduct("libsolidParticle", :libsolidParticle),
    LibraryProduct("libsolidThermo", :libsolidThermo),
    LibraryProduct("libsolverFunctionObjects", :libsolverFunctionObjects),
    LibraryProduct("libspecie", :libspecie),
    LibraryProduct("libspecieTransfer", :libspecieTransfer),
    LibraryProduct("libsurfaceFilmDerivedFvPatchFields", :libsurfaceFilmDerivedFvPatchFields),
    LibraryProduct("libsurfaceFilmModels", :libsurfaceFilmModels),
    LibraryProduct("libsurfMesh", :libsurfMesh),
    LibraryProduct("libtabulatedWallFunctions", :libtabulatedWallFunctions),
    LibraryProduct("libthermalBaffleModels", :libthermalBaffleModels),
    LibraryProduct("libthermophysicalProperties", :libthermophysicalProperties),
    LibraryProduct("libthermophysicalTransportModels", :libthermophysicalTransportModels),
    LibraryProduct("libtopoChangerFvMesh", :libtopoChangerFvMesh),
    LibraryProduct("libtriSurface", :libtriSurface),
    LibraryProduct("libtwoPhaseMixture", :libtwoPhaseMixture),
    LibraryProduct("libtwoPhaseMixtureThermo", :libtwoPhaseMixtureThermo),
    LibraryProduct("libtwoPhaseProperties", :libtwoPhaseProperties),
    LibraryProduct("libtwoPhaseSurfaceTension", :libtwoPhaseSurfaceTension),
    LibraryProduct("libuserd-foam", :libuserd_foam),
    LibraryProduct("libutilityFunctionObjects", :libutilityFunctionObjects),
    LibraryProduct("libVoFphaseCompressibleMomentumTransportModels", :libVoFphaseCompressibleMomentumTransportModels),
    LibraryProduct("libwaves", :libwaves),
    ExecutableProduct("adiabaticFlameT", :adiabaticFlameT),
    ExecutableProduct("adjointShapeOptimizationFoam", :adjointShapeOptimizationFoam),
    ExecutableProduct("ansysToFoam", :ansysToFoam),
    ExecutableProduct("applyBoundaryLayer", :applyBoundaryLayer),
    ExecutableProduct("attachMesh", :attachMesh),
    ExecutableProduct("autoPatch", :autoPatch),
    ExecutableProduct("autoRefineMesh", :autoRefineMesh),
    ExecutableProduct("blockMesh", :blockMesh),
    ExecutableProduct("boundaryFoam", :boundaryFoam),
    ExecutableProduct("boxTurb", :boxTurb),
    ExecutableProduct("buoyantPimpleFoam", :buoyantPimpleFoam),
    ExecutableProduct("buoyantSimpleFoam", :buoyantSimpleFoam),
    ExecutableProduct("cavitatingFoam", :cavitatingFoam),
    ExecutableProduct("cfx4ToFoam", :cfx4ToFoam),
    ExecutableProduct("changeDictionary", :changeDictionary),
    ExecutableProduct("checkMesh", :checkMesh),
    ExecutableProduct("chemFoam", :chemFoam),
    ExecutableProduct("chemkinToFoam", :chemkinToFoam),
    ExecutableProduct("chtMultiRegionFoam", :chtMultiRegionFoam),
    ExecutableProduct("coalChemistryFoam", :coalChemistryFoam),
    ExecutableProduct("coldEngineFoam", :coldEngineFoam),
    ExecutableProduct("collapseEdges", :collapseEdges),
    ExecutableProduct("combinePatchFaces", :combinePatchFaces),
    ExecutableProduct("compressibleInterFilmFoam", :compressibleInterFilmFoam),
    ExecutableProduct("compressibleInterFoam", :compressibleInterFoam),
    ExecutableProduct("compressibleMultiphaseInterFoam", :compressibleMultiphaseInterFoam),
    ExecutableProduct("createBaffles", :createBaffles),
    ExecutableProduct("createExternalCoupledPatchGeometry", :createExternalCoupledPatchGeometry),
    ExecutableProduct("createPatch", :createPatch),
    ExecutableProduct("datToFoam", :datToFoam),
    ExecutableProduct("decomposePar", :decomposePar),
    ExecutableProduct("deformedGeom", :deformedGeom),
    ExecutableProduct("dnsFoam", :dnsFoam),
    ExecutableProduct("DPMFoam", :DPMFoam),
    ExecutableProduct("driftFluxFoam", :driftFluxFoam),
    ExecutableProduct("dsmcFoam", :dsmcFoam),
    ExecutableProduct("dsmcInitialise", :dsmcInitialise),
    ExecutableProduct("electrostaticFoam", :electrostaticFoam),
    ExecutableProduct("engineCompRatio", :engineCompRatio),
    ExecutableProduct("engineFoam", :engineFoam),
    ExecutableProduct("engineSwirl", :engineSwirl),
    ExecutableProduct("equilibriumCO", :equilibriumCO),
    ExecutableProduct("equilibriumFlameT", :equilibriumFlameT),
    ExecutableProduct("extrude2DMesh", :extrude2DMesh),
    ExecutableProduct("extrudeMesh", :extrudeMesh),
    ExecutableProduct("extrudeToRegionMesh", :extrudeToRegionMesh),
    ExecutableProduct("faceAgglomerate", :faceAgglomerate),
    ExecutableProduct("financialFoam", :financialFoam),
    ExecutableProduct("fireFoam", :fireFoam),
    ExecutableProduct("flattenMesh", :flattenMesh),
    ExecutableProduct("fluent3DMeshToFoam", :fluent3DMeshToFoam),
    ExecutableProduct("fluentMeshToFoam", :fluentMeshToFoam),
    ExecutableProduct("foamDataToFluent", :foamDataToFluent),
    ExecutableProduct("foamDictionary", :foamDictionary),
    ExecutableProduct("foamFormatConvert", :foamFormatConvert),
    ExecutableProduct("foamListTimes", :foamListTimes),
    ExecutableProduct("foamMeshToFluent", :foamMeshToFluent),
    ExecutableProduct("foamSetupCHT", :foamSetupCHT),
    ExecutableProduct("foamToEnsight", :foamToEnsight),
    ExecutableProduct("foamToEnsightParts", :foamToEnsightParts),
    ExecutableProduct("foamToGMV", :foamToGMV),
    ExecutableProduct("foamToStarMesh", :foamToStarMesh),
    ExecutableProduct("foamToSurface", :foamToSurface),
    ExecutableProduct("foamToTetDualMesh", :foamToTetDualMesh),
    ExecutableProduct("foamToVTK", :foamToVTK),
    ExecutableProduct("gambitToFoam", :gambitToFoam),
    ExecutableProduct("gmshToFoam", :gmshToFoam),
    ExecutableProduct("icoFoam", :icoFoam),
    ExecutableProduct("ideasUnvToFoam", :ideasUnvToFoam),
    ExecutableProduct("insideCells", :insideCells),
    ExecutableProduct("interFoam", :interFoam),
    ExecutableProduct("interMixingFoam", :interMixingFoam),
    ExecutableProduct("interPhaseChangeFoam", :interPhaseChangeFoam),
    ExecutableProduct("kivaToFoam", :kivaToFoam),
    ExecutableProduct("laplacianFoam", :laplacianFoam),
    ExecutableProduct("magneticFoam", :magneticFoam),
    ExecutableProduct("mapFields", :mapFields),
    ExecutableProduct("mapFieldsPar", :mapFieldsPar),
    ExecutableProduct("mdEquilibrationFoam", :mdEquilibrationFoam),
    ExecutableProduct("mdFoam", :mdFoam),
    ExecutableProduct("mdInitialise", :mdInitialise),
    ExecutableProduct("mergeMeshes", :mergeMeshes),
    ExecutableProduct("mergeOrSplitBaffles", :mergeOrSplitBaffles),
    ExecutableProduct("mhdFoam", :mhdFoam),
    ExecutableProduct("mirrorMesh", :mirrorMesh),
    ExecutableProduct("mixtureAdiabaticFlameT", :mixtureAdiabaticFlameT),
    ExecutableProduct("modifyMesh", :modifyMesh),
    ExecutableProduct("moveDynamicMesh", :moveDynamicMesh),
    ExecutableProduct("moveEngineMesh", :moveEngineMesh),
    ExecutableProduct("moveMesh", :moveMesh),
    ExecutableProduct("MPPICFoam", :MPPICFoam),
    ExecutableProduct("mshToFoam", :mshToFoam),
    ExecutableProduct("multiphaseEulerFoam", :multiphaseEulerFoam),
    ExecutableProduct("multiphaseInterFoam", :multiphaseInterFoam),
    ExecutableProduct("netgenNeutralToFoam", :netgenNeutralToFoam),
    ExecutableProduct("noise", :noise),
    ExecutableProduct("nonNewtonianIcoFoam", :nonNewtonianIcoFoam),
    ExecutableProduct("objToVTK", :objToVTK),
    ExecutableProduct("orientFaceZone", :orientFaceZone),
    ExecutableProduct("particleFoam", :particleFoam),
    ExecutableProduct("particleTracks", :particleTracks),
    ExecutableProduct("patchSummary", :patchSummary),
    ExecutableProduct("pdfPlot", :pdfPlot),
    ExecutableProduct("PDRFoam", :PDRFoam),
    ExecutableProduct("PDRMesh", :PDRMesh),
    ExecutableProduct("pimpleFoam", :pimpleFoam),
    ExecutableProduct("pisoFoam", :pisoFoam),
    ExecutableProduct("plot3dToFoam", :plot3dToFoam),
    ExecutableProduct("polyDualMesh", :polyDualMesh),
    ExecutableProduct("porousSimpleFoam", :porousSimpleFoam),
    ExecutableProduct("postChannel", :postChannel),
    ExecutableProduct("postProcess", :postProcess),
    ExecutableProduct("potentialFoam", :potentialFoam),
    ExecutableProduct("potentialFreeSurfaceFoam", :potentialFreeSurfaceFoam),
    ExecutableProduct("reactingFoam", :reactingFoam),
    ExecutableProduct("reactingParcelFoam", :reactingParcelFoam),
    ExecutableProduct("reconstructPar", :reconstructPar),
    ExecutableProduct("reconstructParMesh", :reconstructParMesh),
    ExecutableProduct("redistributePar", :redistributePar),
    ExecutableProduct("refineHexMesh", :refineHexMesh),
    ExecutableProduct("refinementLevel", :refinementLevel),
    ExecutableProduct("refineMesh", :refineMesh),
    ExecutableProduct("refineWallLayer", :refineWallLayer),
    ExecutableProduct("removeFaces", :removeFaces),
    ExecutableProduct("renumberMesh", :renumberMesh),
    ExecutableProduct("rhoCentralFoam", :rhoCentralFoam),
    ExecutableProduct("rhoParticleFoam", :rhoParticleFoam),
    ExecutableProduct("rhoPimpleFoam", :rhoPimpleFoam),
    ExecutableProduct("rhoPorousSimpleFoam", :rhoPorousSimpleFoam),
    ExecutableProduct("rhoReactingBuoyantFoam", :rhoReactingBuoyantFoam),
    ExecutableProduct("rhoReactingFoam", :rhoReactingFoam),
    ExecutableProduct("rhoSimpleFoam", :rhoSimpleFoam),
    ExecutableProduct("rotateMesh", :rotateMesh),
    ExecutableProduct("sammToFoam", :sammToFoam),
    ExecutableProduct("scalarTransportFoam", :scalarTransportFoam),
    ExecutableProduct("selectCells", :selectCells),
    ExecutableProduct("setFields", :setFields),
    ExecutableProduct("setSet", :setSet),
    ExecutableProduct("setsToZones", :setsToZones),
    ExecutableProduct("setWaves", :setWaves),
    ExecutableProduct("shallowWaterFoam", :shallowWaterFoam),
    ExecutableProduct("simpleFoam", :simpleFoam),
    ExecutableProduct("simpleReactingParcelFoam", :simpleReactingParcelFoam),
    ExecutableProduct("singleCellMesh", :singleCellMesh),
    ExecutableProduct("smapToFoam", :smapToFoam),
    ExecutableProduct("snappyHexMesh", :snappyHexMesh),
    ExecutableProduct("solidDisplacementFoam", :solidDisplacementFoam),
    ExecutableProduct("solidEquilibriumDisplacementFoam", :solidEquilibriumDisplacementFoam),
    ExecutableProduct("splitCells", :splitCells),
    ExecutableProduct("splitMesh", :splitMesh),
    ExecutableProduct("splitMeshRegions", :splitMeshRegions),
    ExecutableProduct("sprayFoam", :sprayFoam),
    ExecutableProduct("SRFPimpleFoam", :SRFPimpleFoam),
    ExecutableProduct("SRFSimpleFoam", :SRFSimpleFoam),
    ExecutableProduct("star3ToFoam", :star3ToFoam),
    ExecutableProduct("star4ToFoam", :star4ToFoam),
    ExecutableProduct("steadyParticleTracks", :steadyParticleTracks),
    ExecutableProduct("stitchMesh", :stitchMesh),
    ExecutableProduct("subsetMesh", :subsetMesh),
    ExecutableProduct("surfaceAdd", :surfaceAdd),
    ExecutableProduct("surfaceAutoPatch", :surfaceAutoPatch),
    ExecutableProduct("surfaceBooleanFeatures", :surfaceBooleanFeatures),
    ExecutableProduct("surfaceCheck", :surfaceCheck),
    ExecutableProduct("surfaceClean", :surfaceClean),
    ExecutableProduct("surfaceCoarsen", :surfaceCoarsen),
    ExecutableProduct("surfaceConvert", :surfaceConvert),
    ExecutableProduct("surfaceFeatureConvert", :surfaceFeatureConvert),
    ExecutableProduct("surfaceFeatures", :surfaceFeatures),
    ExecutableProduct("surfaceFind", :surfaceFind),
    ExecutableProduct("surfaceHookUp", :surfaceHookUp),
    ExecutableProduct("surfaceInertia", :surfaceInertia),
    ExecutableProduct("surfaceLambdaMuSmooth", :surfaceLambdaMuSmooth),
    ExecutableProduct("surfaceMeshConvert", :surfaceMeshConvert),
    ExecutableProduct("surfaceMeshConvertTesting", :surfaceMeshConvertTesting),
    ExecutableProduct("surfaceMeshExport", :surfaceMeshExport),
    ExecutableProduct("surfaceMeshImport", :surfaceMeshImport),
    ExecutableProduct("surfaceMeshInfo", :surfaceMeshInfo),
    ExecutableProduct("surfaceMeshTriangulate", :surfaceMeshTriangulate),
    ExecutableProduct("surfaceOrient", :surfaceOrient),
    ExecutableProduct("surfacePointMerge", :surfacePointMerge),
    ExecutableProduct("surfaceRedistributePar", :surfaceRedistributePar),
    ExecutableProduct("surfaceRefineRedGreen", :surfaceRefineRedGreen),
    ExecutableProduct("surfaceSplitByPatch", :surfaceSplitByPatch),
    ExecutableProduct("surfaceSplitByTopology", :surfaceSplitByTopology),
    ExecutableProduct("surfaceSplitNonManifolds", :surfaceSplitNonManifolds),
    ExecutableProduct("surfaceSubset", :surfaceSubset),
    ExecutableProduct("surfaceToPatch", :surfaceToPatch),
    ExecutableProduct("surfaceTransformPoints", :surfaceTransformPoints),
    ExecutableProduct("temporalInterpolate", :temporalInterpolate),
    ExecutableProduct("tetgenToFoam", :tetgenToFoam),
    ExecutableProduct("thermoFoam", :thermoFoam),
    ExecutableProduct("topoSet", :topoSet),
    ExecutableProduct("transformPoints", :transformPoints),
    ExecutableProduct("twoLiquidMixingFoam", :twoLiquidMixingFoam),
    ExecutableProduct("viewFactorsGen", :viewFactorsGen),
    ExecutableProduct("vtkUnstructuredToFoam", :vtkUnstructuredToFoam),
    ExecutableProduct("wallFunctionTable", :wallFunctionTable),
    ExecutableProduct("writeMeshObj", :writeMeshObj),
    ExecutableProduct("XiEngineFoam", :XiEngineFoam),
    ExecutableProduct("XiFoam", :XiFoam),
    ExecutableProduct("zipUpMesh", :zipUpMesh),
]

# Dependencies that must be installed before this package can be built
dependencies = [
    Dependency("MPICH_jll"),
    Dependency("flex_jll"),
    Dependency("SCOTCH_jll"; compat=SCOTCH_VERSION),
    Dependency("PTSCOTCH_jll"),
    Dependency("METIS_jll"),
    Dependency("Zlib_jll"),
]

# Build the tarballs, and possibly a `build.jl` as well.
build_tarballs(ARGS, name, version, sources, script, platforms, products, dependencies; preferred_gcc_version=v"5", julia_compat="1.6")
