diff --git before/gb/Makefile.am after/gb/Makefile.am
index 22e40c3..1fe4a67 100644
--- before/gb/Makefile.am
+++ after/gb/Makefile.am
@@ -1,16 +1,16 @@
 AUTOMAKE_OPTIONS = gnu subdir-objects color-tests
 ACLOCAL_AMFLAGS	=	-I m4
 
-AM_CFLAGS	=	-std=c11 -march=native -Wextra -Wall -Wfloat-equal -Wundef \
+AM_CFLAGS	=	-std=c11 -Wextra -Wall -Wfloat-equal -Wundef \
 						-Wpointer-arith -Wcast-align -Wstrict-prototypes \
 						-Wmissing-prototypes -Wstrict-overflow=1 -Wwrite-strings \
 						-Waggregate-return -Wswitch-default \
 						-Wswitch-enum -Wconversion -Wunreachable-code \
-						-Wno-unused-result -save-temps -fverbose-asm -masm=intel \
+						-Wno-unused-result -save-temps -fverbose-asm \
 						-Werror-implicit-function-declaration -pedantic \
 						-Wformat=2 -Wformat-y2k -Wno-format-extra-args \
 						-Wno-format-zero-length -Wformat-nonliteral \
-						-Wformat-security -Wno-unknown-pragmas -mpopcnt \
+						-Wformat-security -Wno-unknown-pragmas \
 						-funroll-loops -finline-functions -fpic \
 						${OPENMP_CFLAGS} ${CL_CFLAGS} ${GMP_CFLAGS}
 
@@ -34,7 +34,7 @@ EXTRA_DIST=autogen.sh
 pkgconfigdir = $(libdir)/pkgconfig
 pkgconfig_DATA = gb.pc
 
-libgb_la_LDFLAGS = $(LDFLAGS) -release $(RELEASE) -no-undefined -rdynamic
+libgb_la_LDFLAGS = $(LDFLAGS) -no-undefined -rdynamic
 libgb_la_LIBADD = $(LDADD)
 
 SUBDIRS	=	. test
