diff --git before/libsvm-324/Makefile after/libsvm-324/Makefile
index db6ab34..22f0ae0 100644
--- before/libsvm-324/Makefile
+++ after/libsvm-324/Makefile
@@ -1,25 +1,44 @@
-CXX ?= g++
-CFLAGS = -Wall -Wconversion -O3 -fPIC
-SHVER = 2
-OS = $(shell uname)
+CFLAGS_normal = -Wall -Wconversion -O3 -fPIC -DENABLEOPENMP -fopenmp
+CFLAGS_fallback = -Wall -Wconversion -O3 -DDISABLEOPENMP -fPIC
 
 all: svm-train svm-predict svm-scale
 
-lib: svm.o
-	if [ "$(OS)" = "Darwin" ]; then \
-		SHARED_LIB_FLAG="-dynamiclib -Wl,-install_name,libsvm.so.$(SHVER)"; \
-	else \
-		SHARED_LIB_FLAG="-shared -Wl,-soname,libsvm.so.$(SHVER)"; \
-	fi; \
-	$(CXX) $${SHARED_LIB_FLAG} svm.o -o libsvm.so.$(SHVER)
+lib:
+		$(MAKE) lib_normal || $(MAKE) lib_fallback
+
+lib_normal: svm.o
+		if [ "$(OS)" = "Darwin" ]; then \
+			SHARED_LIB_FLAG="-dynamiclib -Wl,-install_name,libsvm.${dlext}"; \
+		else \
+			SHARED_LIB_FLAG="-shared -Wl,-soname,libsvm.so.${dlext}"; \
+		fi; \
+		$(CXX) $${SHARED_LIB_FLAG} -DENABLEOPENMP -fopenmp svm.o -o libsvm.${dlext}
+
+lib_fallback: svm.o
+		if [ "$(OS)" = "Darwin" ]; then \
+			SHARED_LIB_FLAG="-dynamiclib -Wl,-install_name,libsvm.${dlext}"; \
+		else \
+			SHARED_LIB_FLAG="-shared -Wl,-soname,libsvm.so.${dlext}"; \
+		fi; \
+		$(CXX) $${SHARED_LIB_FLAG} -DDISABLEOPENMP svm.o -o libsvm.${dlext}
 
 svm-predict: svm-predict.c svm.o
-	$(CXX) $(CFLAGS) svm-predict.c svm.o -o svm-predict -lm
+		$(CXX) $(CFLAGS) svm-predict.c svm.o -o svm-predict${exeext} -lm
+
 svm-train: svm-train.c svm.o
-	$(CXX) $(CFLAGS) svm-train.c svm.o -o svm-train -lm
+		$(CXX) $(CFLAGS) svm-train.c svm.o -o svm-train${exeext} -lm
+
 svm-scale: svm-scale.c
-	$(CXX) $(CFLAGS) svm-scale.c -o svm-scale
-svm.o: svm.cpp svm.h
-	$(CXX) $(CFLAGS) -c svm.cpp
+		$(CXX) $(CFLAGS) svm-scale.c -o svm-scale${exeext}
+
+svm.o:
+		$(MAKE) svm.o_normal || $(MAKE) svm.o_fallback
+
+svm.o_normal: svm.cpp svm.h
+		$(CXX) $(CFLAGS_normal) -c svm.cpp
+
+svm.o_fallback: svm.cpp svm.h
+		$(CXX) $(CFLAGS_fallblack) -c svm.cpp
+
 clean:
-	rm -f *~ svm.o svm-train svm-predict svm-scale libsvm.so.$(SHVER)
+		rm -f *~ svm.o svm-train${exeext} svm-predict${exeext} svm-scale${exeext} libsvm.${dlext}
