# This file represents what is put into the webUI.
# It is purely for keeping track of the changes we make to the webUI configuration; modifying this file has no effect.
steps:
  - label: ":buildkite: Pipeline upload"
    command: buildkite-agent pipeline upload
    branches: "!gh-pages"
    agents:
      queue: "juliagpu"
