steps:
  - label: "Trigger publishing pipeline"
    agents:
      queue: "yggdrasil"
      arch:  "x86_64"
      os:    "linux"
      # Only run on "sandbox.jl" machines
      sandbox_capable: "true"
    trigger: "yggdrasil-publish"
    build:
      message: "Publish"
      commit:  "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
    async: false # Wait for the publish to finish 
