steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - JuliaCI/julia#v1: # This is the "outer Julia"
          persist_depot_dirs: packages,artifacts,compiled
          version: "1.7"
          depot_hard_size_limit: "68719476736" # 64GB
      - staticfloat/sandbox#v1:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v5.52/yggdrasil.x86_64.tar.gz
          rootfs_treehash: "0000000000000000000000000000000000000000" # TODO: put in the real hash
          workspaces:
            - "/cache/repos:/cache/repos"
      - JuliaCI/julia#v1: # This is the "inner Julia"
          persist_depot_dirs: packages,artifacts,compiled
          version: "1.7"
          depot_hard_size_limit: "68719476736" # 64GB
      - JuliaCI/merge-commit: ~
      - staticfloat/forerunner#v1:
          watch:
            - "**/*/build_tarballs.jl"
          path_processor: .buildkite/path_processors/per-project
          target: .buildkite/generator.jl
          target_type: command
    agents:
      queue: "yggdrasil"
      arch:  "x86_64"
      os:    "linux"
      # Only run on "sandbox.jl" machines
      sandbox_capable: "true"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 10
    env:
      JULIA_PKG_SERVER: us-east.pkg.julialang.org
      # Use eager registry to not have to wait for updates of the conservative registry
      JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
      # Forward JOB_ID_SECRET
      BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET: ${BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET?}
