steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - JuliaCI/julia#v1:
          persist_depot_dirs: packages,artifacts,compiled
          version: "1.7"
          depot_hard_size_limit: "268435456000" # 250GB
      - JuliaCI/merge-commit: ~
      - staticfloat/forerunner#v1:
          watch:
            # Watch only changes within our top-level alphabetical directories
            - "[A-Z]/**"
          path_processor: .buildkite/path_processors/per-project
          target: .buildkite/generator.jl
          target_type: command
    agents:
      queue: "yggdrasil"
      arch:  "x86_64"
      os:    "linux"
      # Only run on "sandbox.jl" machines
      sandbox_capable: "true"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 20
    env:
      JULIA_PKG_SERVER: us-east.pkg.julialang.org
      # Use eager registry to not have to wait for updates of the conservative registry
      JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
      # Forward JOB_ID_SECRET
      BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET: ${BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET?}
    timeout_in_minutes: 60
