steps:
  - label: "Trigger publishing pipeline"
    trigger: "yggdrasil-publish"
    build:
      message: "Publish"
      commit:  "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
    async: false # Wait for the publish to finish 
