steps:
  - label: "Trigger register pipeline"
    trigger: "yggdrasil-register"
    build:
      message: "Register"
      commit:  "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
    async: false # Wait for the publish to finish 
