diff -ru giflib-5.2.2/Makefile giflib-5.2.2.new/Makefile
--- giflib-5.2.2/Makefile	2024-02-18 20:01:50
+++ giflib-5.2.2.new/Makefile	2024-06-28 09:42:05
@@ -14,10 +14,10 @@
 TAR = tar
 INSTALL = install
 
-PREFIX = /usr/local
-BINDIR = $(PREFIX)/bin
-INCDIR = $(PREFIX)/include
-LIBDIR = $(PREFIX)/lib
+PREFIX = $(prefix)
+BINDIR = $(bindir)
+INCDIR = $(includedir)
+LIBDIR = $(libdir)
 MANDIR = $(PREFIX)/share/man
 
 # No user-serviceable parts below this line
@@ -85,19 +85,21 @@
 LIBGIFSOVER	= libgif.$(LIBVER).$(SOEXTENSION)
 LIBUTILSO	= libutil.$(SOEXTENSION)
 LIBUTILSOMAJOR	= libutil.$(LIBMAJOR).$(SOEXTENSION)
+else ifeq ($(UNAME), MSYS_NT-6.3)
+LIBGIFSO	= libgif.$(dlext)
+LIBGIFSOMAJOR	= libgif-$(LIBMAJOR).$(dlext)
+LIBGIFSOVER	= libgif-$(LIBMAJOR).$(dlext)
+LIBUTILSO	= libutil.$(dlext)
+LIBUTILSOMAJOR	= libutil-$(LIBMAJOR).$(dlext)
 endif
 
 all: $(LIBGIFSO) libgif.a $(LIBUTILSO) libutil.a $(UTILS)
-ifeq ($(UNAME), Darwin)
-else
-	$(MAKE) -C doc
-endif
 
 $(UTILS):: libgif.a libutil.a
 
 $(LIBGIFSO): $(OBJECTS) $(HEADERS)
 ifeq ($(UNAME), Darwin)
-	$(CC) $(CFLAGS) -dynamiclib -current_version $(LIBVER) $(OBJECTS) -o $(LIBGIFSO)
+	$(CC) $(CFLAGS) -shared $(LDFLAGS) -current_version 8.0 -Wl,-install_name,$(LIBGIFSOMAJOR) -compatibility_version 8.0 -o $(LIBGIFSO) $(OBJECTS)
 else
 	$(CC) $(CFLAGS) -shared $(LDFLAGS) -Wl,-soname -Wl,$(LIBGIFSOMAJOR) -o $(LIBGIFSO) $(OBJECTS)
 endif
@@ -107,9 +103,9 @@
 
 $(LIBUTILSO): $(UOBJECTS) $(UHEADERS)
 ifeq ($(UNAME), Darwin)
-	$(CC) $(CFLAGS) -dynamiclib -current_version $(LIBVER) $(OBJECTS) -o $(LIBUTILSO)
+	$(CC) $(CFLAGS) -shared $(LDFLAGS) -current_version 8.0 -Wl,-install_name,$(LIBUTILSOMAJOR) -compatibility_version 8.0 -o $(LIBUTILSO) $(UOBJECTS) -L. -lgif
 else
-	$(CC) $(CFLAGS) -shared $(LDFLAGS) -Wl,-soname -Wl,$(LIBUTILMAJOR) -o $(LIBUTILSO) $(UOBJECTS)
+	$(CC) $(CFLAGS) -shared $(LDFLAGS) -Wl,-soname -Wl,$(LIBUTILMAJOR) -o $(LIBUTILSO) $(UOBJECTS) -L. -lgif
 endif
 
 libutil.a: $(UOBJECTS) $(UHEADERS)
@@ -141,7 +137,10 @@
 	$(INSTALL) -d "$(DESTDIR)$(LIBDIR)"
 	$(INSTALL) -m 644 libgif.a "$(DESTDIR)$(LIBDIR)/libgif.a"
 	$(INSTALL) -m 755 $(LIBGIFSO) "$(DESTDIR)$(LIBDIR)/$(LIBGIFSOVER)"
+ifeq ($(UNAME), MSYS_NT-6.3)
+else
 	ln -sf $(LIBGIFSOVER) "$(DESTDIR)$(LIBDIR)/$(LIBGIFSOMAJOR)"
+endif
 	ln -sf $(LIBGIFSOMAJOR) "$(DESTDIR)$(LIBDIR)/$(LIBGIFSO)"
 install-man:
 	$(INSTALL) -d "$(DESTDIR)$(MANDIR)/man1"
