--- a/Makefile	2026-07-25 12:31:23
+++ b/Makefile	2026-07-25 12:58:46
@@ -8,10 +8,10 @@
 # SPDX-FileCopyrightText: Copyright (C) Eric S. Raymond <esr@thyrsus.com>
 # SPDX-License-Identifier: MIT
 
-PREFIX ?= /usr/local
-BINDIR = $(PREFIX)/bin
-INCDIR = $(PREFIX)/include
-LIBDIR = $(PREFIX)/lib
+PREFIX = $(prefix)
+BINDIR = $(bindir)
+INCDIR = $(includedir)
+LIBDIR = $(libdir)
 MANDIR = $(PREFIX)/share/man
 DOCDIR = $(PREFIX)/share/doc/giflib
 
@@ -104,6 +104,12 @@
 LIBGIFSOVER	= libgif.$(LIBVER).$(SOEXTENSION)
 LIBUTILSO	= libutil.$(SOEXTENSION)
 LIBUTILSOMAJOR	= libutil.$(LIBMAJOR).$(SOEXTENSION)
+else ifeq ($(UNAME), MSYS_NT-6.3)
+LIBGIFSO	= libgif.$(dlext)
+LIBGIFSOMAJOR	= libgif-$(LIBMAJOR).$(dlext)
+LIBGIFSOVER	= libgif-$(LIBMAJOR).$(dlext)
+LIBUTILSO	= libutil.$(dlext)
+LIBUTILSOMAJOR	= libutil-$(LIBMAJOR).$(dlext)
 endif
 
 SHARED_LIBS = $(LIBGIFSO) $(LIBUTILSO)
@@ -123,7 +129,7 @@
 
 $(LIBGIFSO): $(OBJECTS) $(HEADERS)
 ifeq ($(UNAME), Darwin)
-	$(CC) $(CFLAGS) -dynamiclib -current_version $(LIBVER) $(OBJECTS) -o $(LIBGIFSO)
+	$(CC) $(CFLAGS) $(CPPFLAGS) -shared $(LDFLAGS) -current_version 8.0 -Wl,-install_name,$(LIBGIFSOMAJOR) -compatibility_version 8.0 -o $(LIBGIFSO) $(OBJECTS)
 else
 	$(CC) $(CFLAGS) $(CPPFLAGS) -shared $(LDFLAGS) -Wl,-soname -Wl,$(LIBGIFSOMAJOR) -o $(LIBGIFSO) $(OBJECTS)
 endif
@@ -133,9 +139,9 @@
 
 $(LIBUTILSO): $(UOBJECTS) $(UHEADERS)
 ifeq ($(UNAME), Darwin)
-	$(CC) $(CFLAGS) -dynamiclib -current_version $(LIBVER) $(UOBJECTS) -o $(LIBUTILSO)
+	$(CC) $(CFLAGS) $(CPPLAGS) -shared $(LDFLAGS) -current_version 8.0 -Wl,-install_name,$(LIBUTILSOMAJOR) -compatibility_version 8.0 -o $(LIBUTILSO) $(UOBJECTS) -L. -lgif
 else
-	$(CC) $(CFLAGS) $(CPPLAGS) -shared $(LDFLAGS) -Wl,-soname -Wl,$(LIBUTILSOMAJOR) -o $(LIBUTILSO) $(UOBJECTS)
+	$(CC) $(CFLAGS) $(CPPLAGS) -shared $(LDFLAGS) -Wl,-soname -Wl,$(LIBUTILSOMAJOR) -o $(LIBUTILSO) $(UOBJECTS) -L. -lgif
 endif
 
 libutil.a: $(UOBJECTS) $(UHEADERS)
@@ -184,7 +190,10 @@
 install-shared-lib:
 	$(INSTALL) -d "$(DESTDIR)$(LIBDIR)"
 	$(INSTALL) -m 755 $(LIBGIFSO) "$(DESTDIR)$(LIBDIR)/$(LIBGIFSOVER)"
+ifeq ($(UNAME), MSYS_NT-6.3)
+else
 	ln -sf $(LIBGIFSOVER) "$(DESTDIR)$(LIBDIR)/$(LIBGIFSOMAJOR)"
+endif
 	ln -sf $(LIBGIFSOMAJOR) "$(DESTDIR)$(LIBDIR)/$(LIBGIFSO)"
 install-lib: install-static-lib install-shared-lib
 install-man:
