set(C_INTERFACE_PLUGIN_HEADERS
  plugins/CInterfacePlugin/src/command/PrepareMissionSequence.hpp
  plugins/CInterfacePlugin/src/factory/CCommandFactory.hpp
  plugins/CInterfacePlugin/src/include/CInterfaceIntro.hpp
  plugins/CInterfacePlugin/src/include/GmatCFunc_defs.hpp
  plugins/CInterfacePlugin/src/plugin/CInterfacePluginFunctions.hpp)

set(DATA_CALLBACK_PLUGIN_HEADERS
  plugins/DataCallbackPlugin/src/base/factory/DataCallbackFactory.hpp
  plugins/DataCallbackPlugin/src/base/include/datacallback_defs.hpp
  plugins/DataCallbackPlugin/src/base/plugin/GmatPluginFunctions.hpp
  plugins/DataCallbackPlugin/src/base/subscriber/DataCallback.hpp)

set(DATA_INTERFACE_PLUGIN_HEADERS
  plugins/DataInterfacePlugin/src/base/command/Set.hpp
  plugins/DataInterfacePlugin/src/base/datainterface/DataInterface.hpp
  plugins/DataInterfacePlugin/src/base/datainterface/FileInterface.hpp
  plugins/DataInterfacePlugin/src/base/datareader/DataReader.hpp
  plugins/DataInterfacePlugin/src/base/datareader/FileReader.hpp
  plugins/DataInterfacePlugin/src/base/datareader/TcopsVHFAscii.hpp
  plugins/DataInterfacePlugin/src/base/datareader/TcopsVHFData.hpp
  plugins/DataInterfacePlugin/src/base/factory/DataInterfaceCommandFactory.hpp
  plugins/DataInterfacePlugin/src/base/factory/DataInterfaceFactory.hpp
  plugins/DataInterfacePlugin/src/base/factory/ReaderFactory.hpp
  plugins/DataInterfacePlugin/src/base/include/DataInterfaceDefs.hpp
  plugins/DataInterfacePlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(EPHEM_PROPAGATOR_PLUGIN_HEADERS
  plugins/EphemPropagatorPlugin/src/base/factory/EphemPropFactory.hpp
  plugins/EphemPropagatorPlugin/src/base/include/ephempropagator_defs.hpp
  plugins/EphemPropagatorPlugin/src/base/plugin/GmatPluginFunctions.hpp
  plugins/EphemPropagatorPlugin/src/base/propagator/Code500Propagator.hpp
  plugins/EphemPropagatorPlugin/src/base/propagator/EphemerisPropagator.hpp
  plugins/EphemPropagatorPlugin/src/base/propagator/SPKPropagator.hpp
  plugins/EphemPropagatorPlugin/src/base/propagator/StkEPropagator.hpp)

set(ESTIMATION_PLUGIN_HEADERS
  plugins/EstimationPlugin/src/base/adapter/AngleAdapterDeg.hpp
  plugins/EstimationPlugin/src/base/adapter/AzimuthAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/DSNRangeAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/DeclinationAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/DopplerAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/ElevationAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/GNDopplerAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/GNRangeAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/GPSAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/PointRangeRateAdapterKps.hpp
  plugins/EstimationPlugin/src/base/adapter/RangeAdapterKm.hpp
  plugins/EstimationPlugin/src/base/adapter/RangeRateAdapterKps.hpp
  plugins/EstimationPlugin/src/base/adapter/RangeSkinAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/RightAscAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/TDRSDopplerAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/TDRSRangeAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/TrackingDataAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/XEastAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/XSouthAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/YEastAdapter.hpp
  plugins/EstimationPlugin/src/base/adapter/YNorthAdapter.hpp
  plugins/EstimationPlugin/src/base/command/RunEstimator.hpp
  plugins/EstimationPlugin/src/base/command/RunSimulator.hpp
  plugins/EstimationPlugin/src/base/datafilter/AcceptFilter.hpp
  plugins/EstimationPlugin/src/base/datafilter/DataFilter.hpp
  plugins/EstimationPlugin/src/base/datafilter/RejectFilter.hpp
  plugins/EstimationPlugin/src/base/errormodel/ErrorModel.hpp
  plugins/EstimationPlugin/src/base/estimator/BatchEstimator.hpp
  plugins/EstimationPlugin/src/base/estimator/BatchEstimatorBase.hpp
  plugins/EstimationPlugin/src/base/estimator/EstimationStateManager.hpp
  plugins/EstimationPlugin/src/base/estimator/Estimator.hpp
  plugins/EstimationPlugin/src/base/estimator/EstimatorException.hpp
  plugins/EstimationPlugin/src/base/estimator/Simulator.hpp
  plugins/EstimationPlugin/src/base/event/EstimationRootFinder.hpp
  plugins/EstimationPlugin/src/base/event/Event.hpp
  plugins/EstimationPlugin/src/base/event/EventData.hpp
  plugins/EstimationPlugin/src/base/event/EventException.hpp
  plugins/EstimationPlugin/src/base/event/EventManager.hpp
  plugins/EstimationPlugin/src/base/factory/DataFileFactory.hpp
  plugins/EstimationPlugin/src/base/factory/ErrorModelFactory.hpp
  plugins/EstimationPlugin/src/base/factory/EstimationCommandFactory.hpp
  plugins/EstimationPlugin/src/base/factory/EstimationDataFilterFactory.hpp
  plugins/EstimationPlugin/src/base/factory/EstimatorFactory.hpp
  plugins/EstimationPlugin/src/base/factory/EstimatorHardwareFactory.hpp
  plugins/EstimationPlugin/src/base/factory/MeasurementModelFactory.hpp
  plugins/EstimationPlugin/src/base/factory/NavPropagatorFactory.hpp
  plugins/EstimationPlugin/src/base/factory/ObTypeFactory.hpp
  plugins/EstimationPlugin/src/base/factory/SignalModelFactory.hpp
  plugins/EstimationPlugin/src/base/hardware/Antenna.hpp
  plugins/EstimationPlugin/src/base/hardware/RFHardware.hpp
  plugins/EstimationPlugin/src/base/hardware/Receiver.hpp
  plugins/EstimationPlugin/src/base/hardware/Sensor.hpp
  plugins/EstimationPlugin/src/base/hardware/Signal.hpp
  plugins/EstimationPlugin/src/base/hardware/Transmitter.hpp
  plugins/EstimationPlugin/src/base/hardware/Transponder.hpp
  plugins/EstimationPlugin/src/base/include/estimation_defs.hpp
  plugins/EstimationPlugin/src/base/measurement/EstimationDefs.hpp
  plugins/EstimationPlugin/src/base/measurement/Ionosphere/Ionosphere.hpp
  plugins/EstimationPlugin/src/base/measurement/MeasurementData.hpp
  plugins/EstimationPlugin/src/base/measurement/MeasurementException.hpp
  plugins/EstimationPlugin/src/base/measurement/MeasurementManager.hpp
  plugins/EstimationPlugin/src/base/measurement/MeasurementModelBase.hpp
  plugins/EstimationPlugin/src/base/measurement/MediaCorrection.hpp
  plugins/EstimationPlugin/src/base/measurement/Troposphere/Troposphere.hpp
  plugins/EstimationPlugin/src/base/measurementfile/B3_obtype.hpp
  plugins/EstimationPlugin/src/base/measurementfile/DataFile.hpp
  plugins/EstimationPlugin/src/base/measurementfile/DataFileAdapter.hpp
  plugins/EstimationPlugin/src/base/measurementfile/GmatData.hpp
  plugins/EstimationPlugin/src/base/measurementfile/GmatObType.hpp
  plugins/EstimationPlugin/src/base/measurementfile/ObType.hpp
  plugins/EstimationPlugin/src/base/measurementfile/ObservationData.hpp
  plugins/EstimationPlugin/src/base/measurementfile/RampTableData.hpp
  plugins/EstimationPlugin/src/base/measurementfile/RampTableType.hpp
  plugins/EstimationPlugin/src/base/measurementmodel/GPSPointMeasureModel.hpp
  plugins/EstimationPlugin/src/base/measurementmodel/MeasureModel.hpp
  plugins/EstimationPlugin/src/base/plugin/GmatPluginFunctions.hpp
  plugins/EstimationPlugin/src/base/propagator/RungeKutta4.hpp
  plugins/EstimationPlugin/src/base/reporter/ProgressReporter.hpp
  plugins/EstimationPlugin/src/base/signal/PassivePhysicalSignal.hpp
  plugins/EstimationPlugin/src/base/signal/PhysicalSignal.hpp
  plugins/EstimationPlugin/src/base/signal/SignalBase.hpp
  plugins/EstimationPlugin/src/base/signal/SignalData.hpp
  plugins/EstimationPlugin/src/base/signal/SignalDataCache.hpp
  plugins/EstimationPlugin/src/base/signal/SinglePointSignal.hpp
  plugins/EstimationPlugin/src/base/tdmReader/TdmErrorHandler.hpp
  plugins/EstimationPlugin/src/base/tdmReader/TdmObType.hpp
  plugins/EstimationPlugin/src/base/tdmReader/TdmReadWriter.hpp
  plugins/EstimationPlugin/src/base/trackingfile/TFSMagicNumbers.hpp
  plugins/EstimationPlugin/src/base/trackingfile/TrackingFileSet.hpp
  plugins/EstimationPlugin/swig/NavigationAPI.hpp)

set(EVENT_LOCATOR_PLUGIN_HEADERS
  plugins/EventLocatorPlugin/src/base/event/ContactEvent.hpp
  plugins/EventLocatorPlugin/src/base/event/ContactResult.hpp
  plugins/EventLocatorPlugin/src/base/event/EclipseEvent.hpp
  plugins/EventLocatorPlugin/src/base/event/EclipseTotalEvent.hpp
  plugins/EventLocatorPlugin/src/base/factory/EventLocatorFactory.hpp
  plugins/EventLocatorPlugin/src/base/include/EventLocatorDefs.hpp
  plugins/EventLocatorPlugin/src/base/locator/ContactLocator.hpp
  plugins/EventLocatorPlugin/src/base/locator/EclipseLocator.hpp
  plugins/EventLocatorPlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(EXTENDED_KALMAN_FILTER_PLUGIN_HEADERS
  plugins/ExtendedKalmanFilterPlugin/src/base/EKF/ExtendedKalmanFilter.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/EKF/SeqEstimator.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/command/RunSmoother.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/factory/EKFCommandFactory.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/factory/ExtendedKalmanFilterFactory.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/factory/ProcessNoiseFactory.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/factory/ProcessNoiseModelFactory.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/factory/SmootherFactory.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/include/kalman_defs.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/noise/LinearProcessNoise.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/noise/NoiseException.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/noise/ProcessNoiseBase.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/noise/ProcessNoiseModel.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/noise/SNCProcessNoise.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/plugin/GmatPluginFunctions.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/smoother/Smoother.hpp
  plugins/ExtendedKalmanFilterPlugin/src/base/smoother/SmootherBase.hpp)

set(EXTRA_PROPAGATORS_PLUGIN_HEADERS
  plugins/ExtraPropagatorsPlugin/src/base/factory/ExtraPropagatorFactory.hpp
  plugins/ExtraPropagatorsPlugin/src/base/include/ExtraPropagatorDefs.hpp
  plugins/ExtraPropagatorsPlugin/src/base/plugin/GmatPluginFunctions.hpp
  plugins/ExtraPropagatorsPlugin/src/base/propagator/BulirschStoer.hpp)

set(FMINCON_OPTIMIZER_PLUGIN_HEADERS
  plugins/FminconOptimizerPlugin/src/base/factory/FminconOptimizerFactory.hpp
  plugins/FminconOptimizerPlugin/src/base/include/fmincon_defs.hpp
  plugins/FminconOptimizerPlugin/src/base/plugin/GmatPluginFunctions.hpp
  plugins/FminconOptimizerPlugin/src/base/solver/FminconOptimizer.hpp)

set(FORMATION_PLUGIN_HEADERS
  plugins/FormationPlugin/src/base/factory/FormationFactory.hpp
  plugins/FormationPlugin/src/base/formation/Formation.hpp
  plugins/FormationPlugin/src/base/include/FormationDefs.hpp
  plugins/FormationPlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(GEOMETRIC_MEASUREMENT_PLUGIN_HEADERS
  plugins/GeometricMeasurementPlugin/src/base/factory/MeasurementFactory.hpp
  plugins/GeometricMeasurementPlugin/src/base/include/geometricmeasurement_defs.hpp
  plugins/GeometricMeasurementPlugin/src/base/measurement/GeometricAzEl.hpp
  plugins/GeometricMeasurementPlugin/src/base/measurement/GeometricRADec.hpp
  plugins/GeometricMeasurementPlugin/src/base/measurement/GeometricRange.hpp
  plugins/GeometricMeasurementPlugin/src/base/measurement/GeometricRangeRate.hpp
  plugins/GeometricMeasurementPlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(GMAT_FUNCTION_PLUGIN_HEADERS
  plugins/GmatFunctionPlugin/src/base/command/CallGmatFunction.hpp
  plugins/GmatFunctionPlugin/src/base/command/Global.hpp
  plugins/GmatFunctionPlugin/src/base/factory/GmatFunctionCommandFactory.hpp
  plugins/GmatFunctionPlugin/src/base/factory/GmatFunctionFactory.hpp
  plugins/GmatFunctionPlugin/src/base/function/GmatFunction.hpp
  plugins/GmatFunctionPlugin/src/base/include/GmatFunctionIntro.hpp
  plugins/GmatFunctionPlugin/src/base/include/GmatFunction_defs.hpp
  plugins/GmatFunctionPlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(MATLAB_INTERFACE_PLUGIN_HEADERS
  plugins/MatlabInterfacePlugin/src/base/command/CallMatlabFunction.hpp
  plugins/MatlabInterfacePlugin/src/base/factory/CallMatlabFunctionFactory.hpp
  plugins/MatlabInterfacePlugin/src/base/factory/MatlabFunctionFactory.hpp
  plugins/MatlabInterfacePlugin/src/base/factory/MatlabInterfaceFactory.hpp
  plugins/MatlabInterfacePlugin/src/base/factory/MatlabWorkspaceFactory.hpp
  plugins/MatlabInterfacePlugin/src/base/function/MatlabFunction.hpp
  plugins/MatlabInterfacePlugin/src/base/include/matlabinterface_defs.hpp
  plugins/MatlabInterfacePlugin/src/base/interface/MatlabInterface.hpp
  plugins/MatlabInterfacePlugin/src/base/matwriter/MatData.hpp
  plugins/MatlabInterfacePlugin/src/base/matwriter/MatWriter.hpp
  plugins/MatlabInterfacePlugin/src/base/matwriter/MatWriterMaker.hpp
  plugins/MatlabInterfacePlugin/src/base/matwriter/RealMatData.hpp
  plugins/MatlabInterfacePlugin/src/base/matwriter/StringMatData.hpp
  plugins/MatlabInterfacePlugin/src/base/plugin/GmatPluginFunctions.hpp
  plugins/MatlabInterfacePlugin/src/base/subscriber/MatlabWorkspace.hpp
  plugins/MatlabInterfacePlugin/src/matlab/gmat_mex/src/MatlabClient.hpp
  plugins/MatlabInterfacePlugin/src/matlab/gmat_mex/src/MatlabConnection.hpp)

set(NEW_PARAMETER_PLUGIN_HEADERS
  plugins/NewParameterPlugin/src/base/factory/NewParameterFactory.hpp
  plugins/NewParameterPlugin/src/base/include/newparameter_defs.hpp
  plugins/NewParameterPlugin/src/base/parameter/AtmosDensity.hpp
  plugins/NewParameterPlugin/src/base/parameter/FMAcceleration.hpp
  plugins/NewParameterPlugin/src/base/parameter/FMDensity.hpp
  plugins/NewParameterPlugin/src/base/parameter/OdeData.hpp
  plugins/NewParameterPlugin/src/base/parameter/OdeReal.hpp
  plugins/NewParameterPlugin/src/base/parameter/SolverData.hpp
  plugins/NewParameterPlugin/src/base/parameter/SolverReal.hpp
  plugins/NewParameterPlugin/src/base/parameter/SolverState.hpp
  plugins/NewParameterPlugin/src/base/parameter/SolverStatus.hpp
  plugins/NewParameterPlugin/src/base/parameter/SolverString.hpp
  plugins/NewParameterPlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(POLYHEDRON_GRAVITY_PLUGIN_HEADERS
  plugins/PolyhedronGravityPlugin/src/base/factory/GravityParameterFactory.hpp
  plugins/PolyhedronGravityPlugin/src/base/factory/PolyhedronGravityModelFactory.hpp
  plugins/PolyhedronGravityPlugin/src/base/gravitymodel/PolyhedronBody.hpp
  plugins/PolyhedronGravityPlugin/src/base/gravitymodel/PolyhedronGravityModel.hpp
  plugins/PolyhedronGravityPlugin/src/base/include/polyhedrongravitymodel_defs.hpp
  plugins/PolyhedronGravityPlugin/src/base/parameter/GravData.hpp
  plugins/PolyhedronGravityPlugin/src/base/parameter/GravReal.hpp
  plugins/PolyhedronGravityPlugin/src/base/parameter/SurfaceHeight.hpp
  plugins/PolyhedronGravityPlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(PRODUCTION_PROPAGATOR_PLUGIN_HEADERS
  plugins/ProductionPropagatorPlugin/src/base/factory/ProductionPropagatorFactory.hpp
  plugins/ProductionPropagatorPlugin/src/base/include/ProductionPropagatorDefs.hpp
  plugins/ProductionPropagatorPlugin/src/base/plugin/GmatPluginFunctions.hpp
  plugins/ProductionPropagatorPlugin/src/base/propagator/PrinceDormand853.hpp)

set(PYTHON_INTERFACE_PLUGIN_HEADERS
  plugins/PythonInterfacePlugin/src/base/command/CallPythonFunction.hpp
  plugins/PythonInterfacePlugin/src/base/factory/PythonCommandFactory.hpp
  plugins/PythonInterfacePlugin/src/base/function/PythonModule.hpp
  plugins/PythonInterfacePlugin/src/base/include/pythoninterface_defs.hpp
  plugins/PythonInterfacePlugin/src/base/interface/PythonInterface.hpp
  plugins/PythonInterfacePlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(SAVE_COMMAND_PLUGIN_HEADERS
  plugins/SaveCommandPlugin/src/base/command/Save.hpp
  plugins/SaveCommandPlugin/src/base/factory/SaveCommandFactory.hpp
  plugins/SaveCommandPlugin/src/base/include/SaveCommandDefs.hpp
  plugins/SaveCommandPlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(SCRIPT_TOOLS_PLUGIN_HEADERS
  plugins/ScriptToolsPlugin/src/base/command/CommandEcho.hpp
  plugins/ScriptToolsPlugin/src/base/factory/CommandEchoFactory.hpp
  plugins/ScriptToolsPlugin/src/base/include/ScriptToolsDefs.hpp
  plugins/ScriptToolsPlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(STATION_PLUGIN_HEADERS
  plugins/StationPlugin/src/base/factory/StationFactory.hpp
  plugins/StationPlugin/src/base/include/StationDefs.hpp
  plugins/StationPlugin/src/base/plugin/GmatPluginFunctions.hpp
  plugins/StationPlugin/src/base/station/GroundStation.hpp
  plugins/StationPlugin/swig/StationAPI.hpp)

set(THRUST_FILE_PLUGIN_HEADERS
  plugins/ThrustFilePlugin/src/base/command/BeginFileThrust.hpp
  plugins/ThrustFilePlugin/src/base/command/EndFileThrust.hpp
  plugins/ThrustFilePlugin/src/base/datareader/ThfDataSegment.hpp
  plugins/ThrustFilePlugin/src/base/datareader/ThrustHistoryFile.hpp
  plugins/ThrustFilePlugin/src/base/datareader/ThrustSegment.hpp
  plugins/ThrustFilePlugin/src/base/factory/ThrustFileCommandFactory.hpp
  plugins/ThrustFilePlugin/src/base/factory/ThrustFileForceFactory.hpp
  plugins/ThrustFilePlugin/src/base/factory/ThrustFileReaderFactory.hpp
  plugins/ThrustFilePlugin/src/base/forcemodel/FileThrust.hpp
  plugins/ThrustFilePlugin/src/base/include/ThrustFileDefs.hpp
  plugins/ThrustFilePlugin/src/base/plugin/GmatPluginFunctions.hpp)

set(YUKON_OPTIMIZER_FACTORY_HEADERS
  plugins/YukonOptimizerPlugin/src/base/factory/YukonOptimizerFactory.hpp
  plugins/YukonOptimizerPlugin/src/base/include/yukon_defs.hpp
  plugins/YukonOptimizerPlugin/src/base/plugin/GmatPluginFunctions.hpp
  plugins/YukonOptimizerPlugin/src/base/solver/GmatProblemInterface.hpp
  plugins/YukonOptimizerPlugin/src/base/solver/MinQP.hpp
  plugins/YukonOptimizerPlugin/src/base/solver/NLPFunctionGenerator.hpp
  plugins/YukonOptimizerPlugin/src/base/solver/Yukon.hpp
  plugins/YukonOptimizerPlugin/src/base/solver/YukonOptions.hpp
  plugins/YukonOptimizerPlugin/src/base/solver/YukonOutput.hpp
  plugins/YukonOptimizerPlugin/src/base/solver/YukonUserProblem.hpp
  plugins/YukonOptimizerPlugin/src/base/solver/Yukonad.hpp)

set(BASE_HEADERS
  src/base/api/APIException.hpp
  src/base/api/APIFunctions.hpp
  src/base/api/APIMessageReceiver.hpp
  src/base/api/ApiClass.hpp
  src/base/api/HelpSystem.hpp
  src/base/asset/AssetException.hpp
  src/base/asset/BodyFixedPoint.hpp
  src/base/asset/GroundstationInterface.hpp
  src/base/attitude/Attitude.hpp
  src/base/attitude/AttitudeException.hpp
  src/base/attitude/CCSDSAttitude.hpp
  src/base/attitude/CSFixed.hpp
  src/base/attitude/Kinematic.hpp
  src/base/attitude/NadirPointing.hpp
  src/base/attitude/PrecessingSpinner.hpp
  src/base/attitude/SpiceAttitude.hpp
  src/base/attitude/Spinner.hpp
  src/base/attitude/ThreeAxisKinematic.hpp
  src/base/burn/Burn.hpp
  src/base/burn/BurnException.hpp
  src/base/burn/FiniteBurn.hpp
  src/base/burn/ImpulsiveBurn.hpp
  src/base/burn/InertialManeuverFrame.hpp
  src/base/burn/ManeuverFrame.hpp
  src/base/burn/ManeuverFrameManager.hpp
  src/base/burn/VnbManeuverFrame.hpp
  src/base/command/Achieve.hpp
  src/base/command/Assignment.hpp
  src/base/command/BeginFiniteBurn.hpp
  src/base/command/BeginFunction.hpp
  src/base/command/BeginMissionSequence.hpp
  src/base/command/BeginScript.hpp
  src/base/command/BranchCommand.hpp
  src/base/command/CallBuiltinGmatFunction.hpp
  src/base/command/CallFunction.hpp
  src/base/command/ClearPlot.hpp
  src/base/command/CommandException.hpp
  src/base/command/CommandUtil.hpp
  src/base/command/ConditionalBranch.hpp
  src/base/command/Create.hpp
  src/base/command/Else.hpp
  src/base/command/ElseIf.hpp
  src/base/command/EndFiniteBurn.hpp
  src/base/command/EndFor.hpp
  src/base/command/EndFunction.hpp
  src/base/command/EndIf.hpp
  src/base/command/EndOptimize.hpp
  src/base/command/EndScript.hpp
  src/base/command/EndTarget.hpp
  src/base/command/EndWhile.hpp
  src/base/command/FindEvents.hpp
  src/base/command/For.hpp
  src/base/command/GmatCommand.hpp
  src/base/command/If.hpp
  src/base/command/ManageObject.hpp
  src/base/command/Maneuver.hpp
  src/base/command/MarkPoint.hpp
  src/base/command/Minimize.hpp
  src/base/command/NoOp.hpp
  src/base/command/NonlinearConstraint.hpp
  src/base/command/Optimize.hpp
  src/base/command/PenDown.hpp
  src/base/command/PenUp.hpp
  src/base/command/PlotCommand.hpp
  src/base/command/Propagate.hpp
  src/base/command/PropagationEnabledCommand.hpp
  src/base/command/RHSEquation.hpp
  src/base/command/Report.hpp
  src/base/command/RunSolver.hpp
  src/base/command/SaveMission.hpp
  src/base/command/SolverBranchCommand.hpp
  src/base/command/SolverSequenceCommand.hpp
  src/base/command/Stop.hpp
  src/base/command/Target.hpp
  src/base/command/Toggle.hpp
  src/base/command/UpdateDynamicData.hpp
  src/base/command/Vary.hpp
  src/base/command/While.hpp
  src/base/command/Write.hpp
  src/base/configs/ConfigManager.hpp
  src/base/configs/ConfigManagerException.hpp
  src/base/configs/ItemManager.hpp
  src/base/configs/PluginItemManager.hpp
  src/base/coordsystem/AxisSystem.hpp
  src/base/coordsystem/BodyFixedAxes.hpp
  src/base/coordsystem/BodyInertialAxes.hpp
  src/base/coordsystem/BodySpinSunAxes.hpp
  src/base/coordsystem/CoordinateBase.hpp
  src/base/coordsystem/CoordinateConverter.hpp
  src/base/coordsystem/CoordinateSystem.hpp
  src/base/coordsystem/CoordinateSystemException.hpp
  src/base/coordsystem/CoordinateTransformation.hpp
  src/base/coordsystem/CoordinateTranslation.hpp
  src/base/coordsystem/DynamicAxes.hpp
  src/base/coordsystem/EquatorAxes.hpp
  src/base/coordsystem/GeocentricSolarEclipticAxes.hpp
  src/base/coordsystem/GeocentricSolarMagneticAxes.hpp
  src/base/coordsystem/IAUFile.hpp
  src/base/coordsystem/ICRFAxes.hpp
  src/base/coordsystem/ICRFFile.hpp
  src/base/coordsystem/ITRFAxes.hpp
  src/base/coordsystem/InertialAxes.hpp
  src/base/coordsystem/ItrfCoefficientsFile.hpp
  src/base/coordsystem/LocalAlignedConstrainedAxes.hpp
  src/base/coordsystem/MJ2000EcAxes.hpp
  src/base/coordsystem/MJ2000EqAxes.hpp
  src/base/coordsystem/MODEcAxes.hpp
  src/base/coordsystem/MODEqAxes.hpp
  src/base/coordsystem/MOEEcAxes.hpp
  src/base/coordsystem/MOEEqAxes.hpp
  src/base/coordsystem/MeanOfDateAxes.hpp
  src/base/coordsystem/ObjectReferencedAxes.hpp
  src/base/coordsystem/TODEcAxes.hpp
  src/base/coordsystem/TODEqAxes.hpp
  src/base/coordsystem/TOEEcAxes.hpp
  src/base/coordsystem/TOEEqAxes.hpp
  src/base/coordsystem/TopocentricAxes.hpp
  src/base/coordsystem/TransformUtil.hpp
  src/base/coordsystem/TrueOfDateAxes.hpp
  src/base/event/EventException.hpp
  src/base/event/EventLocator.hpp
  src/base/event/LocatedEvent.hpp
  src/base/executive/ListenerManager.hpp
  src/base/executive/ListenerManagerInterface.hpp
  src/base/executive/Moderator.hpp
  src/base/executive/PlotInterface.hpp
  src/base/executive/PlotReceiver.hpp
  src/base/executive/Publisher.hpp
  src/base/executive/PublisherException.hpp
  src/base/executive/Sandbox.hpp
  src/base/executive/SandboxException.hpp
  src/base/factory/AssetFactory.hpp
  src/base/factory/AtmosphereFactory.hpp
  src/base/factory/AttitudeFactory.hpp
  src/base/factory/AxisSystemFactory.hpp
  src/base/factory/BurnFactory.hpp
  src/base/factory/CalculatedPointFactory.hpp
  src/base/factory/CelestialBodyFactory.hpp
  src/base/factory/CommandFactory.hpp
  src/base/factory/CoordinateSystemFactory.hpp
  src/base/factory/Factory.hpp
  src/base/factory/FactoryException.hpp
  src/base/factory/FactoryManager.hpp
  src/base/factory/FieldOfViewFactory.hpp
  src/base/factory/FormationFactory.hpp
  src/base/factory/FunctionFactory.hpp
  src/base/factory/HardwareFactory.hpp
  src/base/factory/InterfaceFactory.hpp
  src/base/factory/MathFactory.hpp
  src/base/factory/ODEModelFactory.hpp
  src/base/factory/ParameterFactory.hpp
  src/base/factory/PhysicalModelFactory.hpp
  src/base/factory/PlateFactory.hpp
  src/base/factory/PropSetupFactory.hpp
  src/base/factory/PropagatorFactory.hpp
  src/base/factory/SolarSystemFactory.hpp
  src/base/factory/SolverFactory.hpp
  src/base/factory/SpacecraftFactory.hpp
  src/base/factory/StopConditionFactory.hpp
  src/base/factory/SubscriberFactory.hpp
  src/base/factory/guicomponents/GmatWidget.hpp
  src/base/factory/guicomponents/GuiFactory.hpp
  src/base/factory/guicomponents/PluginWidget.hpp
  src/base/forcemodel/DragForce.hpp
  src/base/forcemodel/EventModel.hpp
  src/base/forcemodel/FiniteThrust.hpp
  src/base/forcemodel/GravityBase.hpp
  src/base/forcemodel/GravityField.hpp
  src/base/forcemodel/HarmonicField.hpp
  src/base/forcemodel/NumericJacobianOriginal.hpp
  src/base/forcemodel/ODEModel.hpp
  src/base/forcemodel/ODEModelException.hpp
  src/base/forcemodel/PhysicalModel.hpp
  src/base/forcemodel/PointMassForce.hpp
  src/base/forcemodel/RelativisticCorrection.hpp
  src/base/forcemodel/SolarRadiationPressure.hpp
  src/base/forcemodel/harmonic/Harmonic.hpp
  src/base/forcemodel/harmonic/HarmonicGravity.hpp
  src/base/foundation/Covariance.hpp
  src/base/foundation/ElementWrapper.hpp
  src/base/foundation/EquationInitializer.hpp
  src/base/foundation/FileUpdaterSVN.hpp
  src/base/foundation/GmatBase.hpp
  src/base/foundation/GmatBaseException.hpp
  src/base/foundation/GmatState.hpp
  src/base/foundation/GmatType.hpp
  src/base/foundation/IChangeListener.hpp
  src/base/foundation/ObjectInitializer.hpp
  src/base/foundation/SpacePoint.hpp
  src/base/foundation/StateManager.hpp
  src/base/foundation/TriggerManager.hpp
  src/base/function/BuiltinGmatFunction.hpp
  src/base/function/ConvertTime.hpp
  src/base/function/Function.hpp
  src/base/function/FunctionException.hpp
  src/base/function/FunctionManager.hpp
  src/base/function/GetEphemStates.hpp
  src/base/function/GetLastState.hpp
  src/base/function/Num2str.hpp
  src/base/function/ObjectManagedFunction.hpp
  src/base/function/Pause.hpp
  src/base/function/RotationMatrix.hpp
  src/base/function/SetSeed.hpp
  src/base/function/Sign.hpp
  src/base/function/Str2num.hpp
  src/base/function/SystemTime.hpp
  src/base/function/UserDefinedFunction.hpp
  src/base/hardware/ChemicalTank.hpp
  src/base/hardware/ChemicalThruster.hpp
  src/base/hardware/ConicalFOV.hpp
  src/base/hardware/CustomFOV.hpp
  src/base/hardware/ElectricTank.hpp
  src/base/hardware/ElectricThruster.hpp
  src/base/hardware/FieldOfView.hpp
  src/base/hardware/FieldOfViewException.hpp
  src/base/hardware/FuelTank.hpp
  src/base/hardware/Hardware.hpp
  src/base/hardware/HardwareException.hpp
  src/base/hardware/NuclearPowerSystem.hpp
  src/base/hardware/PowerSystem.hpp
  src/base/hardware/RectangularFOV.hpp
  src/base/hardware/SolarPowerSystem.hpp
  src/base/hardware/Thruster.hpp
  src/base/include/DoxygenBaseIntro.hpp
  src/base/include/gmatdefs.hpp
  src/base/interface/GmatInterface.hpp
  src/base/interface/Interface.hpp
  src/base/interface/InterfaceException.hpp
  src/base/interface/SocketServer.hpp
  src/base/interpreter/Interpreter.hpp
  src/base/interpreter/InterpreterException.hpp
  src/base/interpreter/MathParser.hpp
  src/base/interpreter/MathTree.hpp
  src/base/interpreter/ScriptInterpreter.hpp
  src/base/interpreter/ScriptReadWriter.hpp
  src/base/interpreter/Validator.hpp
  src/base/math/Abs.hpp
  src/base/math/Acos.hpp
  src/base/math/Acosh.hpp
  src/base/math/Add.hpp
  src/base/math/Asin.hpp
  src/base/math/Asinh.hpp
  src/base/math/Atan.hpp
  src/base/math/Atan2.hpp
  src/base/math/BuiltinFunctionNode.hpp
  src/base/math/Ceil.hpp
  src/base/math/Cos.hpp
  src/base/math/Cosh.hpp
  src/base/math/Cross3.hpp
  src/base/math/DegToRad.hpp
  src/base/math/Determinant.hpp
  src/base/math/Diag.hpp
  src/base/math/Divide.hpp
  src/base/math/EquationWrapper.hpp
  src/base/math/Exp.hpp
  src/base/math/Fix.hpp
  src/base/math/Floor.hpp
  src/base/math/FunctionRunner.hpp
  src/base/math/Inverse.hpp
  src/base/math/Log.hpp
  src/base/math/Log10.hpp
  src/base/math/MathElement.hpp
  src/base/math/MathException.hpp
  src/base/math/MathFunction.hpp
  src/base/math/MathNode.hpp
  src/base/math/Min.hpp
  src/base/math/Mod.hpp
  src/base/math/Multiply.hpp
  src/base/math/Negate.hpp
  src/base/math/Norm.hpp
  src/base/math/NumericFunctionNode.hpp
  src/base/math/Power.hpp
  src/base/math/RadToDeg.hpp
  src/base/math/Rand.hpp
  src/base/math/Randn.hpp
  src/base/math/Sin.hpp
  src/base/math/Sinh.hpp
  src/base/math/Sprintf.hpp
  src/base/math/Sqrt.hpp
  src/base/math/Strcat.hpp
  src/base/math/Strcmp.hpp
  src/base/math/Strfind.hpp
  src/base/math/StringFunctionNode.hpp
  src/base/math/Strrep.hpp
  src/base/math/Subtract.hpp
  src/base/math/Tan.hpp
  src/base/math/Tanh.hpp
  src/base/math/Transpose.hpp
  src/base/parameter/AlternateEquinoctialParameters.hpp
  src/base/parameter/AngularParameters.hpp
  src/base/parameter/Array.hpp
  src/base/parameter/ArrayElementWrapper.hpp
  src/base/parameter/ArrayWrapper.hpp
  src/base/parameter/AttitudeData.hpp
  src/base/parameter/AttitudeParameters.hpp
  src/base/parameter/AttitudeReal.hpp
  src/base/parameter/AttitudeRvector.hpp
  src/base/parameter/AttitudeString.hpp
  src/base/parameter/BallisticMassParameters.hpp
  src/base/parameter/BallisticMassReal.hpp
  src/base/parameter/BooleanWrapper.hpp
  src/base/parameter/BplaneData.hpp
  src/base/parameter/BplaneParameters.hpp
  src/base/parameter/BplaneReal.hpp
  src/base/parameter/BrouwerMeanLongParameters.hpp
  src/base/parameter/BrouwerMeanShortParameters.hpp
  src/base/parameter/BurnData.hpp
  src/base/parameter/BurnParameters.hpp
  src/base/parameter/BurnReal.hpp
  src/base/parameter/CartesianParameters.hpp
  src/base/parameter/DelaunayParameters.hpp
  src/base/parameter/EnvData.hpp
  src/base/parameter/EnvReal.hpp
  src/base/parameter/EquinoctialParameters.hpp
  src/base/parameter/ExpressionParser.hpp
  src/base/parameter/HardwareParameters.hpp
  src/base/parameter/HardwareReal.hpp
  src/base/parameter/IncomingAsymptoteParameters.hpp
  src/base/parameter/KeplerianParameters.hpp
  src/base/parameter/ModEquinoctialParameters.hpp
  src/base/parameter/NumberWrapper.hpp
  src/base/parameter/ObjectPropertyWrapper.hpp
  src/base/parameter/ObjectWrapper.hpp
  src/base/parameter/OnOffWrapper.hpp
  src/base/parameter/OrbitData.hpp
  src/base/parameter/OrbitReal.hpp
  src/base/parameter/OrbitRmat33.hpp
  src/base/parameter/OrbitRmat66.hpp
  src/base/parameter/OrbitRvec6.hpp
  src/base/parameter/OrbitStmParameters.hpp
  src/base/parameter/OrbitalParameters.hpp
  src/base/parameter/OutgoingAsymptoteParameters.hpp
  src/base/parameter/Parameter.hpp
  src/base/parameter/ParameterDatabase.hpp
  src/base/parameter/ParameterDatabaseException.hpp
  src/base/parameter/ParameterException.hpp
  src/base/parameter/ParameterInfo.hpp
  src/base/parameter/ParameterWrapper.hpp
  src/base/parameter/PlanetData.hpp
  src/base/parameter/PlanetParameters.hpp
  src/base/parameter/PlanetReal.hpp
  src/base/parameter/PlanetodeticParameters.hpp
  src/base/parameter/RealVar.hpp
  src/base/parameter/RefData.hpp
  src/base/parameter/Rmat33Var.hpp
  src/base/parameter/Rmat66Var.hpp
  src/base/parameter/Rvec6Var.hpp
  src/base/parameter/RvectorVar.hpp
  src/base/parameter/SpacecraftData.hpp
  src/base/parameter/SphericalParameters.hpp
  src/base/parameter/StringObjectWrapper.hpp
  src/base/parameter/StringVar.hpp
  src/base/parameter/StringWrapper.hpp
  src/base/parameter/TimeData.hpp
  src/base/parameter/TimeParameters.hpp
  src/base/parameter/TimeReal.hpp
  src/base/parameter/TimeString.hpp
  src/base/parameter/Variable.hpp
  src/base/parameter/VariableWrapper.hpp
  src/base/parameter/paramdefs.hpp
  src/base/plugin/DynamicLibrary.hpp
  src/base/plugin/GmatEventHandler.hpp
  src/base/plugin/GuiInterface.hpp
  src/base/propagator/AdamsBashforthMoulton.hpp
  src/base/propagator/Cowell.hpp
  src/base/propagator/DormandElMikkawyPrince68.hpp
  src/base/propagator/Integrator.hpp
  src/base/propagator/PredictorCorrector.hpp
  src/base/propagator/PrinceDormand45.hpp
  src/base/propagator/PrinceDormand78.hpp
  src/base/propagator/PropSetup.hpp
  src/base/propagator/PropSetupException.hpp
  src/base/propagator/PropagationStateManager.hpp
  src/base/propagator/Propagator.hpp
  src/base/propagator/PropagatorException.hpp
  src/base/propagator/RungeKutta.hpp
  src/base/propagator/RungeKutta89.hpp
  src/base/propagator/RungeKuttaFehlberg56.hpp
  src/base/propagator/RungeKuttaNystrom.hpp
  src/base/solarsys/Asteroid.hpp
  src/base/solarsys/AtmosphereException.hpp
  src/base/solarsys/AtmosphereModel.hpp
  src/base/solarsys/Barycenter.hpp
  src/base/solarsys/CalculatedPoint.hpp
  src/base/solarsys/CelestialBody.hpp
  src/base/solarsys/Comet.hpp
  src/base/solarsys/DeFile.hpp
  src/base/solarsys/EphemSmoother.hpp
  src/base/solarsys/ExponentialAtmosphere.hpp
  src/base/solarsys/JacchiaRobertsAtmosphere.hpp
  src/base/solarsys/LibrationPoint.hpp
  src/base/solarsys/MediaCorrectionInterface.hpp
  src/base/solarsys/Moon.hpp
  src/base/solarsys/Msise90Atmosphere.hpp
  src/base/solarsys/Planet.hpp
  src/base/solarsys/PlanetaryEphem.hpp
  src/base/solarsys/PlanetaryEphemException.hpp
  src/base/solarsys/ShadowState.hpp
  src/base/solarsys/SimpleExponentialAtmosphere.hpp
  src/base/solarsys/SlpFile.hpp
  src/base/solarsys/SolarFluxReader.hpp
  src/base/solarsys/SolarSystem.hpp
  src/base/solarsys/SolarSystemException.hpp
  src/base/solarsys/SpecialCelestialPoint.hpp
  src/base/solarsys/Star.hpp
  src/base/solver/DerivativeModel.hpp
  src/base/solver/DifferentialCorrector.hpp
  src/base/solver/ExternalOptimizer.hpp
  src/base/solver/Gradient.hpp
  src/base/solver/ISolverListener.hpp
  src/base/solver/InternalOptimizer.hpp
  src/base/solver/Jacobian.hpp
  src/base/solver/LineSearch.hpp
  src/base/solver/Optimizer.hpp
  src/base/solver/Solver.hpp
  src/base/solver/SolverException.hpp
  src/base/spacecraft/FormationInterface.hpp
  src/base/spacecraft/Plate.hpp
  src/base/spacecraft/SpaceObject.hpp
  src/base/spacecraft/SpaceObjectException.hpp
  src/base/spacecraft/Spacecraft.hpp
  src/base/spacecraft/TextTrajectoryFile.hpp
  src/base/spice/SpiceAttitudeKernelReader.hpp
  src/base/spice/SpiceInterface.hpp
  src/base/spice/SpiceKernelReader.hpp
  src/base/spice/SpiceKernelWriter.hpp
  src/base/spice/SpiceOrbitKernelReader.hpp
  src/base/spice/SpiceOrbitKernelWriter.hpp
  src/base/stopcond/StopCondition.hpp
  src/base/stopcond/StopConditionException.hpp
  src/base/subscriber/DynamicDataDisplay.hpp
  src/base/subscriber/DynamicDataInterface.hpp
  src/base/subscriber/DynamicDataStruct.hpp
  src/base/subscriber/EphemManager.hpp
  src/base/subscriber/EphemWriterCCSDS.hpp
  src/base/subscriber/EphemWriterCode500.hpp
  src/base/subscriber/EphemWriterSPK.hpp
  src/base/subscriber/EphemWriterSTK.hpp
  src/base/subscriber/EphemWriterWithInterpolator.hpp
  src/base/subscriber/EphemerisFile.hpp
  src/base/subscriber/EphemerisWriter.hpp
  src/base/subscriber/GroundTrackPlot.hpp
  src/base/subscriber/MessageWindow.hpp
  src/base/subscriber/OpenGlPlot.hpp
  src/base/subscriber/OrbitPlot.hpp
  src/base/subscriber/OrbitView.hpp
  src/base/subscriber/OwnedPlot.hpp
  src/base/subscriber/ReportFile.hpp
  src/base/subscriber/Subscriber.hpp
  src/base/subscriber/SubscriberException.hpp
  src/base/subscriber/TextEphemFile.hpp
  src/base/subscriber/XyPlot.hpp)

set(CONSOLE_HEADERS
  src/console/ConsoleAppException.hpp
  src/console/ConsoleMessageReceiver.hpp
  src/console/PrintUtility.hpp
  src/console/driver.hpp)

set(UTIL_HEADERS
  src/gmatutil/include/DoxygenApiIntro.hpp
  src/gmatutil/include/utildefs.hpp
  src/gmatutil/util/A1Date.hpp
  src/gmatutil/util/A1Mjd.hpp
  src/gmatutil/util/AngleUtil.hpp
  src/gmatutil/util/ArrayTemplate.hpp
  src/gmatutil/util/AttitudeConversionUtility.hpp
  src/gmatutil/util/AttitudeUtil.hpp
  src/gmatutil/util/BaseException.hpp
  src/gmatutil/util/BodyFixedStateConverter.hpp
  src/gmatutil/util/CCSDSAEMEulerAngleSegment.hpp
  src/gmatutil/util/CCSDSAEMQuaternionSegment.hpp
  src/gmatutil/util/CCSDSAEMReader.hpp
  src/gmatutil/util/CCSDSAEMSegment.hpp
  src/gmatutil/util/CCSDSEMReader.hpp
  src/gmatutil/util/CCSDSEMSegment.hpp
  src/gmatutil/util/CCSDSEMWriter.hpp
  src/gmatutil/util/CCSDSOEMSegment.hpp
  src/gmatutil/util/CCSDSOEMWriter.hpp
  src/gmatutil/util/CalculationUtilities.hpp
  src/gmatutil/util/Code500EphemerisFile.hpp
  src/gmatutil/util/ColorDatabase.hpp
  src/gmatutil/util/ColorTypes.hpp
  src/gmatutil/util/CubicSpline.hpp
  src/gmatutil/util/Date.hpp
  src/gmatutil/util/DateUtil.hpp
  src/gmatutil/util/ElapsedTime.hpp
  src/gmatutil/util/EopFile.hpp
  src/gmatutil/util/Ephemeris.hpp
  src/gmatutil/util/FileManager.hpp
  src/gmatutil/util/FileTypes.hpp
  src/gmatutil/util/FileUtil.hpp
  src/gmatutil/util/Frozen.hpp
  src/gmatutil/util/GmatConstants.hpp
  src/gmatutil/util/GmatDefaults.hpp
  src/gmatutil/util/GmatGlobal.hpp
  src/gmatutil/util/GmatTime.hpp
  src/gmatutil/util/GravityFileUtil.hpp
  src/gmatutil/util/GregorianDate.hpp
  src/gmatutil/util/IFileUpdater.hpp
  src/gmatutil/util/LeapSecsFileReader.hpp
  src/gmatutil/util/Linear.hpp
  src/gmatutil/util/MemoryTracker.hpp
  src/gmatutil/util/MessageInterface.hpp
  src/gmatutil/util/MessageReceiver.hpp
  src/gmatutil/util/NPlateHistoryFileReader.hpp
  src/gmatutil/util/NumericJacobian.hpp
  src/gmatutil/util/OrbitDesignerTime.hpp
  src/gmatutil/util/RandomNumber.hpp
  src/gmatutil/util/RealUtilities.hpp
  src/gmatutil/util/RepeatGroundTrack.hpp
  src/gmatutil/util/RepeatSunSync.hpp
  src/gmatutil/util/RgbColor.hpp
  src/gmatutil/util/Rmatrix.hpp
  src/gmatutil/util/Rmatrix33.hpp
  src/gmatutil/util/Rmatrix66.hpp
  src/gmatutil/util/Rvector.hpp
  src/gmatutil/util/Rvector3.hpp
  src/gmatutil/util/Rvector6.hpp
  src/gmatutil/util/SPADFileReader.hpp
  src/gmatutil/util/STKEphemerisFile.hpp
  src/gmatutil/util/StateConversionUtil.hpp
  src/gmatutil/util/StringTokenizer.hpp
  src/gmatutil/util/StringUtil.hpp
  src/gmatutil/util/SunSync.hpp
  src/gmatutil/util/TableTemplate.hpp
  src/gmatutil/util/TextParser.hpp
  src/gmatutil/util/TimeSystemConverter.hpp
  src/gmatutil/util/TimeTypes.hpp
  src/gmatutil/util/UtcDate.hpp
  src/gmatutil/util/UtilityException.hpp
  src/gmatutil/util/datawriter/DataBucket.hpp
  src/gmatutil/util/datawriter/DataWriter.hpp
  src/gmatutil/util/datawriter/DataWriterInterface.hpp
  src/gmatutil/util/datawriter/DataWriterMaker.hpp
  src/gmatutil/util/datawriter/WriterData.hpp
  src/gmatutil/util/interpolator/BrentDekkerZero.hpp
  src/gmatutil/util/interpolator/CubicSplineInterpolator.hpp
  src/gmatutil/util/interpolator/HermiteInterpolator.hpp
  src/gmatutil/util/interpolator/Interpolator.hpp
  src/gmatutil/util/interpolator/InterpolatorException.hpp
  src/gmatutil/util/interpolator/LagrangeInterpolator.hpp
  src/gmatutil/util/interpolator/LinearInterpolator.hpp
  src/gmatutil/util/interpolator/NotAKnotInterpolator.hpp
  src/gmatutil/util/matrixoperations/CholeskyFactorization.hpp
  src/gmatutil/util/matrixoperations/LUFactorization.hpp
  src/gmatutil/util/matrixoperations/MatrixFactorization.hpp
  src/gmatutil/util/matrixoperations/QRFactorization.hpp
  src/gmatutil/util/matrixoperations/SchurFactorization.hpp)

set(API_HEADERS
  swig/GmatAPI.hpp)

