set(CInterface_HEADERS
  command/PrepareMissionSequence.hpp
  factory/CCommandFactory.hpp
  include/CInterfaceIntro.hpp
  include/GmatCFunc_defs.hpp
  plugin/CInterfacePluginFunctions.hpp)

set(DataCallback_HEADERS
  factory/DataCallbackFactory.hpp
  include/datacallback_defs.hpp
  plugin/GmatPluginFunctions.hpp
  subscriber/DataCallback.hpp)

set(DataInterface_HEADERS
  command/Set.hpp
  datainterface/DataInterface.hpp
  datainterface/FileInterface.hpp
  datareader/DataReader.hpp
  datareader/FileReader.hpp
  datareader/TcopsVHFAscii.hpp
  datareader/TcopsVHFData.hpp
  factory/DataInterfaceCommandFactory.hpp
  factory/DataInterfaceFactory.hpp
  factory/ReaderFactory.hpp
  include/DataInterfaceDefs.hpp
  plugin/GmatPluginFunctions.hpp)

set(EphemPropagator_HEADERS
  factory/EphemPropFactory.hpp
  include/ephempropagator_defs.hpp
  plugin/GmatPluginFunctions.hpp
  propagator/Code500Propagator.hpp
  propagator/EphemerisPropagator.hpp
  propagator/SPKPropagator.hpp
  propagator/StkEPropagator.hpp)

set(GmatEstimation_HEADERS
  adapter/AngleAdapterDeg.hpp
  adapter/AzimuthAdapter.hpp
  adapter/DSNRangeAdapter.hpp
  adapter/DeclinationAdapter.hpp
  adapter/DopplerAdapter.hpp
  adapter/ElevationAdapter.hpp
  adapter/GNDopplerAdapter.hpp
  adapter/GNRangeAdapter.hpp
  adapter/GPSAdapter.hpp
  adapter/PointRangeRateAdapterKps.hpp
  adapter/RangeAdapterKm.hpp
  adapter/RangeRateAdapterKps.hpp
  adapter/RangeSkinAdapter.hpp
  adapter/RightAscAdapter.hpp
  adapter/TDRSDopplerAdapter.hpp
  adapter/TDRSRangeAdapter.hpp
  adapter/TrackingDataAdapter.hpp
  adapter/XEastAdapter.hpp
  adapter/XSouthAdapter.hpp
  adapter/YEastAdapter.hpp
  adapter/YNorthAdapter.hpp
  command/RunEstimator.hpp
  command/RunSimulator.hpp
  datafilter/AcceptFilter.hpp
  datafilter/DataFilter.hpp
  datafilter/RejectFilter.hpp
  errormodel/ErrorModel.hpp
  estimator/BatchEstimator.hpp
  estimator/BatchEstimatorBase.hpp
  estimator/EstimationStateManager.hpp
  estimator/Estimator.hpp
  estimator/EstimatorException.hpp
  estimator/Simulator.hpp
  event/EstimationRootFinder.hpp
  event/Event.hpp
  event/EventData.hpp
  event/EventException.hpp
  event/EventManager.hpp
  factory/DataFileFactory.hpp
  factory/ErrorModelFactory.hpp
  factory/EstimationCommandFactory.hpp
  factory/EstimationDataFilterFactory.hpp
  factory/EstimatorFactory.hpp
  factory/EstimatorHardwareFactory.hpp
  factory/MeasurementModelFactory.hpp
  factory/NavPropagatorFactory.hpp
  factory/ObTypeFactory.hpp
  factory/SignalModelFactory.hpp
  hardware/Antenna.hpp
  hardware/RFHardware.hpp
  hardware/Receiver.hpp
  hardware/Sensor.hpp
  hardware/Signal.hpp
  hardware/Transmitter.hpp
  hardware/Transponder.hpp
  include/estimation_defs.hpp
  measurement/EstimationDefs.hpp
  measurement/Ionosphere/Ionosphere.hpp
  measurement/MeasurementData.hpp
  measurement/MeasurementException.hpp
  measurement/MeasurementManager.hpp
  measurement/MeasurementModelBase.hpp
  measurement/MediaCorrection.hpp
  measurement/Troposphere/Troposphere.hpp
  measurementfile/B3_obtype.hpp
  measurementfile/DataFile.hpp
  measurementfile/DataFileAdapter.hpp
  measurementfile/GmatData.hpp
  measurementfile/GmatObType.hpp
  measurementfile/ObType.hpp
  measurementfile/ObservationData.hpp
  measurementfile/RampTableData.hpp
  measurementfile/RampTableType.hpp
  measurementmodel/GPSPointMeasureModel.hpp
  measurementmodel/MeasureModel.hpp
  plugin/GmatPluginFunctions.hpp
  propagator/RungeKutta4.hpp
  reporter/ProgressReporter.hpp
  signal/PassivePhysicalSignal.hpp
  signal/PhysicalSignal.hpp
  signal/SignalBase.hpp
  signal/SignalData.hpp
  signal/SignalDataCache.hpp
  signal/SinglePointSignal.hpp
  tdmReader/TdmErrorHandler.hpp
  tdmReader/TdmObType.hpp
  tdmReader/TdmReadWriter.hpp
  trackingfile/TFSMagicNumbers.hpp
  trackingfile/TrackingFileSet.hpp)

set(EventLocator_HEADERS
  event/ContactEvent.hpp
  event/ContactResult.hpp
  event/EclipseEvent.hpp
  event/EclipseTotalEvent.hpp
  factory/EventLocatorFactory.hpp
  include/EventLocatorDefs.hpp
  locator/ContactLocator.hpp
  locator/EclipseLocator.hpp
  plugin/GmatPluginFunctions.hpp)

set(EKF_HEADERS
  EKF/ExtendedKalmanFilter.hpp
  EKF/SeqEstimator.hpp
  command/RunSmoother.hpp
  factory/EKFCommandFactory.hpp
  factory/ExtendedKalmanFilterFactory.hpp
  factory/ProcessNoiseFactory.hpp
  factory/ProcessNoiseModelFactory.hpp
  factory/SmootherFactory.hpp
  include/kalman_defs.hpp
  noise/LinearProcessNoise.hpp
  noise/NoiseException.hpp
  noise/ProcessNoiseBase.hpp
  noise/ProcessNoiseModel.hpp
  noise/SNCProcessNoise.hpp
  plugin/GmatPluginFunctions.hpp
  smoother/Smoother.hpp
  smoother/SmootherBase.hpp)

set(ExtraPropagators_HEADERS
  factory/ExtraPropagatorFactory.hpp
  include/ExtraPropagatorDefs.hpp
  plugin/GmatPluginFunctions.hpp
  propagator/BulirschStoer.hpp)

set(FminconOptimizer_HEADERS
  factory/FminconOptimizerFactory.hpp
  include/fmincon_defs.hpp
  plugin/GmatPluginFunctions.hpp
  solver/FminconOptimizer.hpp)

set(Formation_HEADERS
  factory/FormationFactory.hpp
  formation/Formation.hpp
  include/FormationDefs.hpp
  plugin/GmatPluginFunctions.hpp)

set(GeometricMeasurement_HEADERS
  factory/MeasurementFactory.hpp
  include/geometricmeasurement_defs.hpp
  measurement/GeometricAzEl.hpp
  measurement/GeometricRADec.hpp
  measurement/GeometricRange.hpp
  measurement/GeometricRangeRate.hpp
  plugin/GmatPluginFunctions.hpp)

set(GmatFunction_HEADERS
  command/CallGmatFunction.hpp
  command/Global.hpp
  factory/GmatFunctionCommandFactory.hpp
  factory/GmatFunctionFactory.hpp
  function/GmatFunction.hpp
  include/GmatFunctionIntro.hpp
  include/GmatFunction_defs.hpp
  plugin/GmatPluginFunctions.hpp)

set(MatlabInterface_HEADERS
  command/CallMatlabFunction.hpp
  factory/CallMatlabFunctionFactory.hpp
  factory/MatlabFunctionFactory.hpp
  factory/MatlabInterfaceFactory.hpp
  factory/MatlabWorkspaceFactory.hpp
  function/MatlabFunction.hpp
  include/matlabinterface_defs.hpp
  interface/MatlabInterface.hpp
  matwriter/MatData.hpp
  matwriter/MatWriter.hpp
  matwriter/MatWriterMaker.hpp
  matwriter/RealMatData.hpp
  matwriter/StringMatData.hpp
  plugin/GmatPluginFunctions.hpp
  subscriber/MatlabWorkspace.hpp
  matlab/gmat_mex/src/MatlabClient.hpp
  matlab/gmat_mex/src/MatlabConnection.hpp)

set(NewParameters_HEADERS
  factory/NewParameterFactory.hpp
  include/newparameter_defs.hpp
  parameter/AtmosDensity.hpp
  parameter/FMAcceleration.hpp
  parameter/FMDensity.hpp
  parameter/OdeData.hpp
  parameter/OdeReal.hpp
  parameter/SolverData.hpp
  parameter/SolverReal.hpp
  parameter/SolverState.hpp
  parameter/SolverStatus.hpp
  parameter/SolverString.hpp
  plugin/GmatPluginFunctions.hpp)

set(PolyhedronGravity_HEADERS
  factory/GravityParameterFactory.hpp
  factory/PolyhedronGravityModelFactory.hpp
  gravitymodel/PolyhedronBody.hpp
  gravitymodel/PolyhedronGravityModel.hpp
  include/polyhedrongravitymodel_defs.hpp
  parameter/GravData.hpp
  parameter/GravReal.hpp
  parameter/SurfaceHeight.hpp
  plugin/GmatPluginFunctions.hpp)

set(ProductionPropagators_HEADERS
  factory/ProductionPropagatorFactory.hpp
  include/ProductionPropagatorDefs.hpp
  plugin/GmatPluginFunctions.hpp
  propagator/PrinceDormand853.hpp)

set(PythonInterface_HEADERS
  command/CallPythonFunction.hpp
  factory/PythonCommandFactory.hpp
  function/PythonModule.hpp
  include/pythoninterface_defs.hpp
  interface/PythonInterface.hpp
  plugin/GmatPluginFunctions.hpp)

set(SaveCommand_HEADERS
  command/Save.hpp
  factory/SaveCommandFactory.hpp
  include/SaveCommandDefs.hpp
  plugin/GmatPluginFunctions.hpp)

set(ScriptTools_HEADERS
  command/CommandEcho.hpp
  factory/CommandEchoFactory.hpp
  include/ScriptToolsDefs.hpp
  plugin/GmatPluginFunctions.hpp)

set(Station_HEADERS
  factory/StationFactory.hpp
  include/StationDefs.hpp
  plugin/GmatPluginFunctions.hpp
  station/GroundStation.hpp)

set(ThrustFile_HEADERS
  command/BeginFileThrust.hpp
  command/EndFileThrust.hpp
  datareader/ThfDataSegment.hpp
  datareader/ThrustHistoryFile.hpp
  datareader/ThrustSegment.hpp
  factory/ThrustFileCommandFactory.hpp
  factory/ThrustFileForceFactory.hpp
  factory/ThrustFileReaderFactory.hpp
  forcemodel/FileThrust.hpp
  include/ThrustFileDefs.hpp
  plugin/GmatPluginFunctions.hpp)

set(YukonOptimizer_HEADERS
  factory/YukonOptimizerFactory.hpp
  include/yukon_defs.hpp
  plugin/GmatPluginFunctions.hpp
  solver/GmatProblemInterface.hpp
  solver/MinQP.hpp
  solver/NLPFunctionGenerator.hpp
  solver/Yukon.hpp
  solver/YukonOptions.hpp
  solver/YukonOutput.hpp
  solver/YukonUserProblem.hpp
  solver/Yukonad.hpp)

set(BASE_HEADERS
  src/base/api/APIException.hpp
  src/base/api/APIFunctions.hpp
  src/base/api/APIMessageReceiver.hpp
  src/base/api/ApiClass.hpp
  src/base/api/HelpSystem.hpp
  src/base/asset/AssetException.hpp
  src/base/asset/BodyFixedPoint.hpp
  src/base/asset/GroundstationInterface.hpp
  src/base/attitude/Attitude.hpp
  src/base/attitude/AttitudeException.hpp
  src/base/attitude/CCSDSAttitude.hpp
  src/base/attitude/CSFixed.hpp
  src/base/attitude/Kinematic.hpp
  src/base/attitude/NadirPointing.hpp
  src/base/attitude/PrecessingSpinner.hpp
  src/base/attitude/SpiceAttitude.hpp
  src/base/attitude/Spinner.hpp
  src/base/attitude/ThreeAxisKinematic.hpp
  src/base/burn/Burn.hpp
  src/base/burn/BurnException.hpp
  src/base/burn/FiniteBurn.hpp
  src/base/burn/ImpulsiveBurn.hpp
  src/base/burn/InertialManeuverFrame.hpp
  src/base/burn/ManeuverFrame.hpp
  src/base/burn/ManeuverFrameManager.hpp
  src/base/burn/VnbManeuverFrame.hpp
  src/base/command/Achieve.hpp
  src/base/command/Assignment.hpp
  src/base/command/BeginFiniteBurn.hpp
  src/base/command/BeginFunction.hpp
  src/base/command/BeginMissionSequence.hpp
  src/base/command/BeginScript.hpp
  src/base/command/BranchCommand.hpp
  src/base/command/CallBuiltinGmatFunction.hpp
  src/base/command/CallFunction.hpp
  src/base/command/ClearPlot.hpp
  src/base/command/CommandException.hpp
  src/base/command/CommandUtil.hpp
  src/base/command/ConditionalBranch.hpp
  src/base/command/Create.hpp
  src/base/command/Else.hpp
  src/base/command/ElseIf.hpp
  src/base/command/EndFiniteBurn.hpp
  src/base/command/EndFor.hpp
  src/base/command/EndFunction.hpp
  src/base/command/EndIf.hpp
  src/base/command/EndOptimize.hpp
  src/base/command/EndScript.hpp
  src/base/command/EndTarget.hpp
  src/base/command/EndWhile.hpp
  src/base/command/FindEvents.hpp
  src/base/command/For.hpp
  src/base/command/GmatCommand.hpp
  src/base/command/If.hpp
  src/base/command/ManageObject.hpp
  src/base/command/Maneuver.hpp
  src/base/command/MarkPoint.hpp
  src/base/command/Minimize.hpp
  src/base/command/NoOp.hpp
  src/base/command/NonlinearConstraint.hpp
  src/base/command/Optimize.hpp
  src/base/command/PenDown.hpp
  src/base/command/PenUp.hpp
  src/base/command/PlotCommand.hpp
  src/base/command/Propagate.hpp
  src/base/command/PropagationEnabledCommand.hpp
  src/base/command/RHSEquation.hpp
  src/base/command/Report.hpp
  src/base/command/RunSolver.hpp
  src/base/command/SaveMission.hpp
  src/base/command/SolverBranchCommand.hpp
  src/base/command/SolverSequenceCommand.hpp
  src/base/command/Stop.hpp
  src/base/command/Target.hpp
  src/base/command/Toggle.hpp
  src/base/command/UpdateDynamicData.hpp
  src/base/command/Vary.hpp
  src/base/command/While.hpp
  src/base/command/Write.hpp
  src/base/configs/ConfigManager.hpp
  src/base/configs/ConfigManagerException.hpp
  src/base/configs/ItemManager.hpp
  src/base/configs/PluginItemManager.hpp
  src/base/coordsystem/AxisSystem.hpp
  src/base/coordsystem/BodyFixedAxes.hpp
  src/base/coordsystem/BodyInertialAxes.hpp
  src/base/coordsystem/BodySpinSunAxes.hpp
  src/base/coordsystem/CoordinateBase.hpp
  src/base/coordsystem/CoordinateConverter.hpp
  src/base/coordsystem/CoordinateSystem.hpp
  src/base/coordsystem/CoordinateSystemException.hpp
  src/base/coordsystem/CoordinateTransformation.hpp
  src/base/coordsystem/CoordinateTranslation.hpp
  src/base/coordsystem/DynamicAxes.hpp
  src/base/coordsystem/EquatorAxes.hpp
  src/base/coordsystem/GeocentricSolarEclipticAxes.hpp
  src/base/coordsystem/GeocentricSolarMagneticAxes.hpp
  src/base/coordsystem/IAUFile.hpp
  src/base/coordsystem/ICRFAxes.hpp
  src/base/coordsystem/ICRFFile.hpp
  src/base/coordsystem/ITRFAxes.hpp
  src/base/coordsystem/InertialAxes.hpp
  src/base/coordsystem/ItrfCoefficientsFile.hpp
  src/base/coordsystem/LocalAlignedConstrainedAxes.hpp
  src/base/coordsystem/MJ2000EcAxes.hpp
  src/base/coordsystem/MJ2000EqAxes.hpp
  src/base/coordsystem/MODEcAxes.hpp
  src/base/coordsystem/MODEqAxes.hpp
  src/base/coordsystem/MOEEcAxes.hpp
  src/base/coordsystem/MOEEqAxes.hpp
  src/base/coordsystem/MeanOfDateAxes.hpp
  src/base/coordsystem/ObjectReferencedAxes.hpp
  src/base/coordsystem/TODEcAxes.hpp
  src/base/coordsystem/TODEqAxes.hpp
  src/base/coordsystem/TOEEcAxes.hpp
  src/base/coordsystem/TOEEqAxes.hpp
  src/base/coordsystem/TopocentricAxes.hpp
  src/base/coordsystem/TransformUtil.hpp
  src/base/coordsystem/TrueOfDateAxes.hpp
  src/base/event/EventException.hpp
  src/base/event/EventLocator.hpp
  src/base/event/LocatedEvent.hpp
  src/base/executive/ListenerManager.hpp
  src/base/executive/ListenerManagerInterface.hpp
  src/base/executive/Moderator.hpp
  src/base/executive/PlotInterface.hpp
  src/base/executive/PlotReceiver.hpp
  src/base/executive/Publisher.hpp
  src/base/executive/PublisherException.hpp
  src/base/executive/Sandbox.hpp
  src/base/executive/SandboxException.hpp
  src/base/factory/AssetFactory.hpp
  src/base/factory/AtmosphereFactory.hpp
  src/base/factory/AttitudeFactory.hpp
  src/base/factory/AxisSystemFactory.hpp
  src/base/factory/BurnFactory.hpp
  src/base/factory/CalculatedPointFactory.hpp
  src/base/factory/CelestialBodyFactory.hpp
  src/base/factory/CommandFactory.hpp
  src/base/factory/CoordinateSystemFactory.hpp
  src/base/factory/Factory.hpp
  src/base/factory/FactoryException.hpp
  src/base/factory/FactoryManager.hpp
  src/base/factory/FieldOfViewFactory.hpp
  src/base/factory/FormationFactory.hpp
  src/base/factory/FunctionFactory.hpp
  src/base/factory/HardwareFactory.hpp
  src/base/factory/InterfaceFactory.hpp
  src/base/factory/MathFactory.hpp
  src/base/factory/ODEModelFactory.hpp
  src/base/factory/ParameterFactory.hpp
  src/base/factory/PhysicalModelFactory.hpp
  src/base/factory/PlateFactory.hpp
  src/base/factory/PropSetupFactory.hpp
  src/base/factory/PropagatorFactory.hpp
  src/base/factory/SolarSystemFactory.hpp
  src/base/factory/SolverFactory.hpp
  src/base/factory/SpacecraftFactory.hpp
  src/base/factory/StopConditionFactory.hpp
  src/base/factory/SubscriberFactory.hpp
  src/base/factory/guicomponents/GmatWidget.hpp
  src/base/factory/guicomponents/GuiFactory.hpp
  src/base/factory/guicomponents/PluginWidget.hpp
  src/base/forcemodel/DragForce.hpp
  src/base/forcemodel/EventModel.hpp
  src/base/forcemodel/FiniteThrust.hpp
  src/base/forcemodel/GravityBase.hpp
  src/base/forcemodel/GravityField.hpp
  src/base/forcemodel/HarmonicField.hpp
  src/base/forcemodel/NumericJacobianOriginal.hpp
  src/base/forcemodel/ODEModel.hpp
  src/base/forcemodel/ODEModelException.hpp
  src/base/forcemodel/PhysicalModel.hpp
  src/base/forcemodel/PointMassForce.hpp
  src/base/forcemodel/RelativisticCorrection.hpp
  src/base/forcemodel/SolarRadiationPressure.hpp
  src/base/forcemodel/harmonic/Harmonic.hpp
  src/base/forcemodel/harmonic/HarmonicGravity.hpp
  src/base/foundation/Covariance.hpp
  src/base/foundation/ElementWrapper.hpp
  src/base/foundation/EquationInitializer.hpp
  src/base/foundation/FileUpdaterSVN.hpp
  src/base/foundation/GmatBase.hpp
  src/base/foundation/GmatBaseException.hpp
  src/base/foundation/GmatState.hpp
  src/base/foundation/GmatType.hpp
  src/base/foundation/IChangeListener.hpp
  src/base/foundation/ObjectInitializer.hpp
  src/base/foundation/SpacePoint.hpp
  src/base/foundation/StateManager.hpp
  src/base/foundation/TriggerManager.hpp
  src/base/function/BuiltinGmatFunction.hpp
  src/base/function/ConvertTime.hpp
  src/base/function/Function.hpp
  src/base/function/FunctionException.hpp
  src/base/function/FunctionManager.hpp
  src/base/function/GetEphemStates.hpp
  src/base/function/GetLastState.hpp
  src/base/function/Num2str.hpp
  src/base/function/ObjectManagedFunction.hpp
  src/base/function/Pause.hpp
  src/base/function/RotationMatrix.hpp
  src/base/function/SetSeed.hpp
  src/base/function/Sign.hpp
  src/base/function/Str2num.hpp
  src/base/function/SystemTime.hpp
  src/base/function/UserDefinedFunction.hpp
  src/base/hardware/ChemicalTank.hpp
  src/base/hardware/ChemicalThruster.hpp
  src/base/hardware/ConicalFOV.hpp
  src/base/hardware/CustomFOV.hpp
  src/base/hardware/ElectricTank.hpp
  src/base/hardware/ElectricThruster.hpp
  src/base/hardware/FieldOfView.hpp
  src/base/hardware/FieldOfViewException.hpp
  src/base/hardware/FuelTank.hpp
  src/base/hardware/Hardware.hpp
  src/base/hardware/HardwareException.hpp
  src/base/hardware/NuclearPowerSystem.hpp
  src/base/hardware/PowerSystem.hpp
  src/base/hardware/RectangularFOV.hpp
  src/base/hardware/SolarPowerSystem.hpp
  src/base/hardware/Thruster.hpp
  src/base/include/DoxygenBaseIntro.hpp
  src/base/include/gmatdefs.hpp
  src/base/interface/GmatInterface.hpp
  src/base/interface/Interface.hpp
  src/base/interface/InterfaceException.hpp
  src/base/interface/SocketServer.hpp
  src/base/interpreter/Interpreter.hpp
  src/base/interpreter/InterpreterException.hpp
  src/base/interpreter/MathParser.hpp
  src/base/interpreter/MathTree.hpp
  src/base/interpreter/ScriptInterpreter.hpp
  src/base/interpreter/ScriptReadWriter.hpp
  src/base/interpreter/Validator.hpp
  src/base/math/Abs.hpp
  src/base/math/Acos.hpp
  src/base/math/Acosh.hpp
  src/base/math/Add.hpp
  src/base/math/Asin.hpp
  src/base/math/Asinh.hpp
  src/base/math/Atan.hpp
  src/base/math/Atan2.hpp
  src/base/math/BuiltinFunctionNode.hpp
  src/base/math/Ceil.hpp
  src/base/math/Cos.hpp
  src/base/math/Cosh.hpp
  src/base/math/Cross3.hpp
  src/base/math/DegToRad.hpp
  src/base/math/Determinant.hpp
  src/base/math/Diag.hpp
  src/base/math/Divide.hpp
  src/base/math/EquationWrapper.hpp
  src/base/math/Exp.hpp
  src/base/math/Fix.hpp
  src/base/math/Floor.hpp
  src/base/math/FunctionRunner.hpp
  src/base/math/Inverse.hpp
  src/base/math/Log.hpp
  src/base/math/Log10.hpp
  src/base/math/MathElement.hpp
  src/base/math/MathException.hpp
  src/base/math/MathFunction.hpp
  src/base/math/MathNode.hpp
  src/base/math/Min.hpp
  src/base/math/Mod.hpp
  src/base/math/Multiply.hpp
  src/base/math/Negate.hpp
  src/base/math/Norm.hpp
  src/base/math/NumericFunctionNode.hpp
  src/base/math/Power.hpp
  src/base/math/RadToDeg.hpp
  src/base/math/Rand.hpp
  src/base/math/Randn.hpp
  src/base/math/Sin.hpp
  src/base/math/Sinh.hpp
  src/base/math/Sprintf.hpp
  src/base/math/Sqrt.hpp
  src/base/math/Strcat.hpp
  src/base/math/Strcmp.hpp
  src/base/math/Strfind.hpp
  src/base/math/StringFunctionNode.hpp
  src/base/math/Strrep.hpp
  src/base/math/Subtract.hpp
  src/base/math/Tan.hpp
  src/base/math/Tanh.hpp
  src/base/math/Transpose.hpp
  src/base/parameter/AlternateEquinoctialParameters.hpp
  src/base/parameter/AngularParameters.hpp
  src/base/parameter/Array.hpp
  src/base/parameter/ArrayElementWrapper.hpp
  src/base/parameter/ArrayWrapper.hpp
  src/base/parameter/AttitudeData.hpp
  src/base/parameter/AttitudeParameters.hpp
  src/base/parameter/AttitudeReal.hpp
  src/base/parameter/AttitudeRvector.hpp
  src/base/parameter/AttitudeString.hpp
  src/base/parameter/BallisticMassParameters.hpp
  src/base/parameter/BallisticMassReal.hpp
  src/base/parameter/BooleanWrapper.hpp
  src/base/parameter/BplaneData.hpp
  src/base/parameter/BplaneParameters.hpp
  src/base/parameter/BplaneReal.hpp
  src/base/parameter/BrouwerMeanLongParameters.hpp
  src/base/parameter/BrouwerMeanShortParameters.hpp
  src/base/parameter/BurnData.hpp
  src/base/parameter/BurnParameters.hpp
  src/base/parameter/BurnReal.hpp
  src/base/parameter/CartesianParameters.hpp
  src/base/parameter/DelaunayParameters.hpp
  src/base/parameter/EnvData.hpp
  src/base/parameter/EnvReal.hpp
  src/base/parameter/EquinoctialParameters.hpp
  src/base/parameter/ExpressionParser.hpp
  src/base/parameter/HardwareParameters.hpp
  src/base/parameter/HardwareReal.hpp
  src/base/parameter/IncomingAsymptoteParameters.hpp
  src/base/parameter/KeplerianParameters.hpp
  src/base/parameter/ModEquinoctialParameters.hpp
  src/base/parameter/NumberWrapper.hpp
  src/base/parameter/ObjectPropertyWrapper.hpp
  src/base/parameter/ObjectWrapper.hpp
  src/base/parameter/OnOffWrapper.hpp
  src/base/parameter/OrbitData.hpp
  src/base/parameter/OrbitReal.hpp
  src/base/parameter/OrbitRmat33.hpp
  src/base/parameter/OrbitRmat66.hpp
  src/base/parameter/OrbitRvec6.hpp
  src/base/parameter/OrbitStmParameters.hpp
  src/base/parameter/OrbitalParameters.hpp
  src/base/parameter/OutgoingAsymptoteParameters.hpp
  src/base/parameter/Parameter.hpp
  src/base/parameter/ParameterDatabase.hpp
  src/base/parameter/ParameterDatabaseException.hpp
  src/base/parameter/ParameterException.hpp
  src/base/parameter/ParameterInfo.hpp
  src/base/parameter/ParameterWrapper.hpp
  src/base/parameter/PlanetData.hpp
  src/base/parameter/PlanetParameters.hpp
  src/base/parameter/PlanetReal.hpp
  src/base/parameter/PlanetodeticParameters.hpp
  src/base/parameter/RealVar.hpp
  src/base/parameter/RefData.hpp
  src/base/parameter/Rmat33Var.hpp
  src/base/parameter/Rmat66Var.hpp
  src/base/parameter/Rvec6Var.hpp
  src/base/parameter/RvectorVar.hpp
  src/base/parameter/SpacecraftData.hpp
  src/base/parameter/SphericalParameters.hpp
  src/base/parameter/StringObjectWrapper.hpp
  src/base/parameter/StringVar.hpp
  src/base/parameter/StringWrapper.hpp
  src/base/parameter/TimeData.hpp
  src/base/parameter/TimeParameters.hpp
  src/base/parameter/TimeReal.hpp
  src/base/parameter/TimeString.hpp
  src/base/parameter/Variable.hpp
  src/base/parameter/VariableWrapper.hpp
  src/base/parameter/paramdefs.hpp
  src/base/plugin/DynamicLibrary.hpp
  src/base/plugin/GmatEventHandler.hpp
  src/base/plugin/GuiInterface.hpp
  src/base/propagator/AdamsBashforthMoulton.hpp
  src/base/propagator/Cowell.hpp
  src/base/propagator/DormandElMikkawyPrince68.hpp
  src/base/propagator/Integrator.hpp
  src/base/propagator/PredictorCorrector.hpp
  src/base/propagator/PrinceDormand45.hpp
  src/base/propagator/PrinceDormand78.hpp
  src/base/propagator/PropSetup.hpp
  src/base/propagator/PropSetupException.hpp
  src/base/propagator/PropagationStateManager.hpp
  src/base/propagator/Propagator.hpp
  src/base/propagator/PropagatorException.hpp
  src/base/propagator/RungeKutta.hpp
  src/base/propagator/RungeKutta89.hpp
  src/base/propagator/RungeKuttaFehlberg56.hpp
  src/base/propagator/RungeKuttaNystrom.hpp
  src/base/solarsys/Asteroid.hpp
  src/base/solarsys/AtmosphereException.hpp
  src/base/solarsys/AtmosphereModel.hpp
  src/base/solarsys/Barycenter.hpp
  src/base/solarsys/CalculatedPoint.hpp
  src/base/solarsys/CelestialBody.hpp
  src/base/solarsys/Comet.hpp
  src/base/solarsys/DeFile.hpp
  src/base/solarsys/EphemSmoother.hpp
  src/base/solarsys/ExponentialAtmosphere.hpp
  src/base/solarsys/JacchiaRobertsAtmosphere.hpp
  src/base/solarsys/LibrationPoint.hpp
  src/base/solarsys/MediaCorrectionInterface.hpp
  src/base/solarsys/Moon.hpp
  src/base/solarsys/Msise90Atmosphere.hpp
  src/base/solarsys/Planet.hpp
  src/base/solarsys/PlanetaryEphem.hpp
  src/base/solarsys/PlanetaryEphemException.hpp
  src/base/solarsys/ShadowState.hpp
  src/base/solarsys/SimpleExponentialAtmosphere.hpp
  src/base/solarsys/SlpFile.hpp
  src/base/solarsys/SolarFluxReader.hpp
  src/base/solarsys/SolarSystem.hpp
  src/base/solarsys/SolarSystemException.hpp
  src/base/solarsys/SpecialCelestialPoint.hpp
  src/base/solarsys/Star.hpp
  src/base/solver/DerivativeModel.hpp
  src/base/solver/DifferentialCorrector.hpp
  src/base/solver/ExternalOptimizer.hpp
  src/base/solver/Gradient.hpp
  src/base/solver/ISolverListener.hpp
  src/base/solver/InternalOptimizer.hpp
  src/base/solver/Jacobian.hpp
  src/base/solver/LineSearch.hpp
  src/base/solver/Optimizer.hpp
  src/base/solver/Solver.hpp
  src/base/solver/SolverException.hpp
  src/base/spacecraft/FormationInterface.hpp
  src/base/spacecraft/Plate.hpp
  src/base/spacecraft/SpaceObject.hpp
  src/base/spacecraft/SpaceObjectException.hpp
  src/base/spacecraft/Spacecraft.hpp
  src/base/spacecraft/TextTrajectoryFile.hpp
  src/base/spice/SpiceAttitudeKernelReader.hpp
  src/base/spice/SpiceInterface.hpp
  src/base/spice/SpiceKernelReader.hpp
  src/base/spice/SpiceKernelWriter.hpp
  src/base/spice/SpiceOrbitKernelReader.hpp
  src/base/spice/SpiceOrbitKernelWriter.hpp
  src/base/stopcond/StopCondition.hpp
  src/base/stopcond/StopConditionException.hpp
  src/base/subscriber/DynamicDataDisplay.hpp
  src/base/subscriber/DynamicDataInterface.hpp
  src/base/subscriber/DynamicDataStruct.hpp
  src/base/subscriber/EphemManager.hpp
  src/base/subscriber/EphemWriterCCSDS.hpp
  src/base/subscriber/EphemWriterCode500.hpp
  src/base/subscriber/EphemWriterSPK.hpp
  src/base/subscriber/EphemWriterSTK.hpp
  src/base/subscriber/EphemWriterWithInterpolator.hpp
  src/base/subscriber/EphemerisFile.hpp
  src/base/subscriber/EphemerisWriter.hpp
  src/base/subscriber/GroundTrackPlot.hpp
  src/base/subscriber/MessageWindow.hpp
  src/base/subscriber/OpenGlPlot.hpp
  src/base/subscriber/OrbitPlot.hpp
  src/base/subscriber/OrbitView.hpp
  src/base/subscriber/OwnedPlot.hpp
  src/base/subscriber/ReportFile.hpp
  src/base/subscriber/Subscriber.hpp
  src/base/subscriber/SubscriberException.hpp
  src/base/subscriber/TextEphemFile.hpp
  src/base/subscriber/XyPlot.hpp)

set(CONSOLE_HEADERS
  src/console/ConsoleAppException.hpp
  src/console/ConsoleMessageReceiver.hpp
  src/console/PrintUtility.hpp
  src/console/driver.hpp)

set(UTIL_HEADERS
  src/gmatutil/include/DoxygenApiIntro.hpp
  src/gmatutil/include/utildefs.hpp
  src/gmatutil/util/A1Date.hpp
  src/gmatutil/util/A1Mjd.hpp
  src/gmatutil/util/AngleUtil.hpp
  src/gmatutil/util/ArrayTemplate.hpp
  src/gmatutil/util/AttitudeConversionUtility.hpp
  src/gmatutil/util/AttitudeUtil.hpp
  src/gmatutil/util/BaseException.hpp
  src/gmatutil/util/BodyFixedStateConverter.hpp
  src/gmatutil/util/CCSDSAEMEulerAngleSegment.hpp
  src/gmatutil/util/CCSDSAEMQuaternionSegment.hpp
  src/gmatutil/util/CCSDSAEMReader.hpp
  src/gmatutil/util/CCSDSAEMSegment.hpp
  src/gmatutil/util/CCSDSEMReader.hpp
  src/gmatutil/util/CCSDSEMSegment.hpp
  src/gmatutil/util/CCSDSEMWriter.hpp
  src/gmatutil/util/CCSDSOEMSegment.hpp
  src/gmatutil/util/CCSDSOEMWriter.hpp
  src/gmatutil/util/CalculationUtilities.hpp
  src/gmatutil/util/Code500EphemerisFile.hpp
  src/gmatutil/util/ColorDatabase.hpp
  src/gmatutil/util/ColorTypes.hpp
  src/gmatutil/util/CubicSpline.hpp
  src/gmatutil/util/Date.hpp
  src/gmatutil/util/DateUtil.hpp
  src/gmatutil/util/ElapsedTime.hpp
  src/gmatutil/util/EopFile.hpp
  src/gmatutil/util/Ephemeris.hpp
  src/gmatutil/util/FileManager.hpp
  src/gmatutil/util/FileTypes.hpp
  src/gmatutil/util/FileUtil.hpp
  src/gmatutil/util/Frozen.hpp
  src/gmatutil/util/GmatConstants.hpp
  src/gmatutil/util/GmatDefaults.hpp
  src/gmatutil/util/GmatGlobal.hpp
  src/gmatutil/util/GmatTime.hpp
  src/gmatutil/util/GravityFileUtil.hpp
  src/gmatutil/util/GregorianDate.hpp
  src/gmatutil/util/IFileUpdater.hpp
  src/gmatutil/util/LeapSecsFileReader.hpp
  src/gmatutil/util/Linear.hpp
  src/gmatutil/util/MemoryTracker.hpp
  src/gmatutil/util/MessageInterface.hpp
  src/gmatutil/util/MessageReceiver.hpp
  src/gmatutil/util/NPlateHistoryFileReader.hpp
  src/gmatutil/util/NumericJacobian.hpp
  src/gmatutil/util/OrbitDesignerTime.hpp
  src/gmatutil/util/RandomNumber.hpp
  src/gmatutil/util/RealUtilities.hpp
  src/gmatutil/util/RepeatGroundTrack.hpp
  src/gmatutil/util/RepeatSunSync.hpp
  src/gmatutil/util/RgbColor.hpp
  src/gmatutil/util/Rmatrix.hpp
  src/gmatutil/util/Rmatrix33.hpp
  src/gmatutil/util/Rmatrix66.hpp
  src/gmatutil/util/Rvector.hpp
  src/gmatutil/util/Rvector3.hpp
  src/gmatutil/util/Rvector6.hpp
  src/gmatutil/util/SPADFileReader.hpp
  src/gmatutil/util/STKEphemerisFile.hpp
  src/gmatutil/util/StateConversionUtil.hpp
  src/gmatutil/util/StringTokenizer.hpp
  src/gmatutil/util/StringUtil.hpp
  src/gmatutil/util/SunSync.hpp
  src/gmatutil/util/TableTemplate.hpp
  src/gmatutil/util/TextParser.hpp
  src/gmatutil/util/TimeSystemConverter.hpp
  src/gmatutil/util/TimeTypes.hpp
  src/gmatutil/util/UtcDate.hpp
  src/gmatutil/util/UtilityException.hpp
  src/gmatutil/util/datawriter/DataBucket.hpp
  src/gmatutil/util/datawriter/DataWriter.hpp
  src/gmatutil/util/datawriter/DataWriterInterface.hpp
  src/gmatutil/util/datawriter/DataWriterMaker.hpp
  src/gmatutil/util/datawriter/WriterData.hpp
  src/gmatutil/util/interpolator/BrentDekkerZero.hpp
  src/gmatutil/util/interpolator/CubicSplineInterpolator.hpp
  src/gmatutil/util/interpolator/HermiteInterpolator.hpp
  src/gmatutil/util/interpolator/Interpolator.hpp
  src/gmatutil/util/interpolator/InterpolatorException.hpp
  src/gmatutil/util/interpolator/LagrangeInterpolator.hpp
  src/gmatutil/util/interpolator/LinearInterpolator.hpp
  src/gmatutil/util/interpolator/NotAKnotInterpolator.hpp
  src/gmatutil/util/matrixoperations/CholeskyFactorization.hpp
  src/gmatutil/util/matrixoperations/LUFactorization.hpp
  src/gmatutil/util/matrixoperations/MatrixFactorization.hpp
  src/gmatutil/util/matrixoperations/QRFactorization.hpp
  src/gmatutil/util/matrixoperations/SchurFactorization.hpp)

set(API_HEADERS
  plugins/EstimationPlugin/swig/NavigationAPI.hpp
  plugins/StationPlugin/swig/StationAPI.hpp
  swig/GmatAPI.hpp)

install(FILES ${API_HEADERS} DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/GMAT")

