#!/bin/bash

# we want to use the target's `llvm-config`, but alas that binary is not executable,
# so we use the one from the HostDependency, patching what it reports where necessary.

host_tool=${host_prefix}/tools/llvm-config
target_tool=${prefix}/tools/llvm-config

host_prefix=$(dirname $(dirname $(realpath ${host_tool})))
target_prefix=$(dirname $(dirname $(realpath ${target_tool})))

# figure out the target arch (e.g. AArch64) by looking at the include headers:
# $target_prefix/include/llvm/Config/llvm-config.h: #define LLVM_NATIVE_ARCH AArch64
target_arch=$(grep -m 1 '#define LLVM_NATIVE_ARCH' $target_prefix/include/llvm/Config/llvm-config.h | \
    sed -e 's|.*#define LLVM_NATIVE_ARCH \(.*\)|\1|g')

# replace the host X86 target from --targets-built, and wipe targets that aren't available everywhere
if [[ "$@" == *--targets-built* ]]; then
    $host_tool "$@" | sed -e "s/X86/$target_arch/" -e "s/NVPTX//" -e "s/AMDGPU//"
    exit 0
fi

# get rid of -lrt and -ldl on Windows
if [[ "${target}" == *mingw*  && "$@" == *--system-libs* ]]; then
    echo -n "-lntdll "
    $host_tool "$@" | sed -e 's/-lrt//' -e 's/-ldl//'
    exit 0
fi
if [[ "${target}" == *freebsd*  && "$@" == *--system-libs* ]]; then
    echo -n "-lexecinfo "
fi

# when asking for --libs, filter out host ones that may not be available on the target
# (e.g. LLVMIntelJITEvents) and replace the host X86 backend with the target backend.
# NVPTX is also not available everywhere (i.e. not on macOS) so get rid of it.
if [[ "$@" == *--libs* ]]; then
    # strip libraries that may not be availble
    output=$($host_tool "$@" | sed -e 's/-lLLVMIntelJIT[[:alnum:]]*//g' \
                                   -e 's/-lLLVMPerfJITEvents[[:alnum:]]*//g' \
                                   -e "s/-lLLVMNVPTX[[:alnum:]]*//g" \
                                   -e "s/-lLLVMAMDGPU[[:alnum:]]*//g")

    if [[ $target_arch != X86 ]]; then
        # determine all target libraries by looking at the filesystem
        # (the exact set may be different, e.g., X86 has TargetMCA, AArch64 has Utils)
        libs=()
        for lib in $target_prefix/lib/libLLVM$target_arch*.a; do
            # push -l$LIB to the array, minus the lib prefix and .a suffix
            # e.g. libLLVMX86Disassembler.a -> -lLLVMX86Disassembler
            libs+=("-l$(basename $lib | sed 's/^lib//;s/\.a$//')")
        done
        libstr="${libs[@]}"

        output=$(echo $output | sed -e "s|-lLLVMX86[[:alnum:]]*|$libstr|" \
                                    -e "s/-lLLVMX86[[:alnum:]]*//g")
    fi

    echo $output
    exit 0
fi

# simply reuse the host tool for everything else, replacing the host with target prefix
$host_tool "$@" | sed -e "s|$host_prefix|$target_prefix|g"
