diff --git before/liblinear/Makefile after/liblinear/Makefile
index ac287b3..15125b0 100644
--- before/liblinear/Makefile
+++ after/liblinear/Makefile
@@ -6,21 +6,21 @@ LIBS = blas/blas.a
 SHVER = 5
 OS = $(shell uname)
 ifeq ($(OS),Darwin)
-	SHARED_LIB_FLAG = -dynamiclib -Wl,-install_name,liblinear.so.$(SHVER)
+	SHARED_LIB_FLAG = -dynamiclib -Wl,-install_name,liblinear.${dlext}
 else
-	SHARED_LIB_FLAG = -shared -Wl,-soname,liblinear.so.$(SHVER)
+	SHARED_LIB_FLAG = -shared -Wl,-soname,liblinear.${dlext}
 endif
 
 all: train predict
 
 lib: linear.o newton.o blas/blas.a
-	$(CXX) $(SHARED_LIB_FLAG) linear.o newton.o blas/blas.a -o liblinear.so.$(SHVER)
+	$(CXX) $(SHARED_LIB_FLAG) linear.o newton.o blas/blas.a -o liblinear.${dlext}
 
 train: newton.o linear.o train.c blas/blas.a
-	$(CXX) $(CFLAGS) -o train train.c newton.o linear.o $(LIBS)
+	$(CXX) $(CFLAGS) -o train${exeext} train.c newton.o linear.o $(LIBS)
 
 predict: newton.o linear.o predict.c blas/blas.a
-	$(CXX) $(CFLAGS) -o predict predict.c newton.o linear.o $(LIBS)
+	$(CXX) $(CFLAGS) -o predict${exeext} predict.c newton.o linear.o $(LIBS)
 
 newton.o: newton.cpp newton.h
 	$(CXX) $(CFLAGS) -c -o newton.o newton.cpp
@@ -34,4 +34,4 @@ blas/blas.a: blas/*.c blas/*.h
 clean:
 	make -C blas clean
 	make -C matlab clean
-	rm -f *~ newton.o linear.o train predict liblinear.so.$(SHVER)
+	rm -f *~ newton.o linear.o train predict liblinear.${dlext}
