# Note that this script can accept some limited command-line arguments, run
# `julia build_tarballs.jl --help` to see a usage message.
using BinaryBuilder

name = "ASL2"
version = v"0.1.0"

# Collection of sources required to build ASL2.
#
# solvers2.tgz is the multithreaded variant of the AMPL Solver Library, in
# which evaluations operate on a given EvalWorkspace, so that distinct
# workspaces may evaluate concurrently from different threads.
#
# Beware: netlib updates solvers2.tgz in place without changing the URL, so
# the checksum below will break whenever upstream releases a new snapshot.
# Run `curl -L http://netlib.org/ampl/solvers2.tgz | sha256sum` to refresh it.
# A more reproducible alternative is a GitSource of the mirror
# https://github.com/ampl/asl (build from src/solvers2).
sources = [
    ArchiveSource("http://netlib.org/ampl/solvers2.tgz",
                  "6867edd76810d5f2e4e62678d705c16f31d5276c7edfe6fc7ffbcbb8f259803d"),
    DirectorySource("./bundled")
]

# Bash recipe for building across all platforms
script = raw"""
cd $WORKSPACE/srcdir/solvers2/
head -17 asl.h > LICENSE.txt
mkdir -p ${includedir}
mkdir -p ${libdir}

all_load="--whole-archive"
noall_load="--no-whole-archive"
makefile="makefile.u"
cflags=""

# arith.h is normally generated by compiling and *running* arithchk.c, which
# is impossible when cross-compiling; use pre-generated per-target copies.
# arithchk.c is identical in solvers.tgz and solvers2.tgz, so these files
# are the same as in the ASL recipe.
if [[ -f $WORKSPACE/srcdir/asl-extra/arith.h.$target ]]; then
    cp $WORKSPACE/srcdir/asl-extra/arith.h.$target ./arith.h
fi

if [[ "${target}" == "arm-linux-musleabihf" ]]; then
    cp $WORKSPACE/srcdir/asl-extra/arith.h.arm-linux-gnueabihf ./arith.h
elif [[ $target == "i686-linux-musl" ]]; then
    cp $WORKSPACE/srcdir/asl-extra/arith.h.i686-linux-gnu ./arith.h
elif [[ "${target}" == "aarch64-linux-musl" ]]; then
    cp $WORKSPACE/srcdir/asl-extra/arith.h.aarch64-linux-gnu ./arith.h
elif [[ "${target}" == *-freebsd* ]]; then
    cp $WORKSPACE/srcdir/asl-extra/arith.h.x86_64-linux-gnu ./arith.h
    cflags="-D__XSI_VISIBLE=1"
elif [[ "${target}" == *-mingw* ]]; then
    makefile="$WORKSPACE/srcdir/asl-extra/makefile.mingw"
elif [[ "${target}" == *-apple-* ]]; then
    all_load="-all_load"
    noall_load="-noall_load"
fi

make -f $makefile CC="$CC" CFLAGS="-O -fPIC $cflags"
c++ -fPIC -shared -I$WORKSPACE/srcdir/asl-extra -I. $WORKSPACE/srcdir/asl-extra/aslinterface.cc -Wl,${all_load} amplsolver.a -Wl,${noall_load} -o libasl2.${dlext}
cp libasl2.${dlext} ${libdir}
cp *.h ${includedir}
cp *.hd ${includedir}
install_license LICENSE.txt
"""

# These are the platforms we will build for by default, unless further
# platforms are passed in on the command line
platforms = supported_platforms(;experimental=true)

# The products that we will ensure are always built.
# The library is named libasl2 so that ASL_jll and ASL2_jll can coexist in
# the same process; the asl_* entry points keep their names, since each JLL
# resolves symbols within its own library handle.
products = [
    LibraryProduct("libasl2", :libasl2)
]

# Dependencies that must be installed before this package can be built
dependencies = Dependency[
]

# Build the tarballs
build_tarballs(ARGS, name, version, sources, script, platforms, products, dependencies, julia_compat = "1.6")
