--- Makefile.am.orig
+++ Makefile.am
@@ -18,8 +18,13 @@
        libspatialindex.la \
        src/capi/libsidxc.la

-libspatialindex_la_LDFLAGS = -version-info 4:1:0 -no-undefined -lstdc++
-libspatialindex_c_la_LDFLAGS = -version-info 4:1:0 -no-undefined -lstdc++
+# Dummy file to force C++ linking, see this page for more details:
+# https://www.gnu.org/software/automake/manual/html_node/Libtool-Convenience-Libraries.html
+nodist_EXTRA_libspatialindex_la_SOURCES = dummy.cxx
+nodist_EXTRA_libspatialindex_c_la_SOURCES = dummy.cxx
+
+libspatialindex_la_LDFLAGS = -version-info 4:1:0 -no-undefined
+libspatialindex_c_la_LDFLAGS = -version-info 4:1:0 -no-undefined

 EXTRA_DIST = INSTALL.WIN \
              spatialindex.sln \
