--- /dev/null
+++ b/src/Makefile.inc
@@ -0,0 +1,21 @@
+EXE             =
+LIB             = .$(dlext)
+OBJ             = .o
+
+MAKE            = make
+AR              = $(CC)
+ARFLAGS         = -shared -o
+CAT             = cat
+CCS             = $(CC)
+CCP             = mpicc
+CCD             = $(CC) -I$(prefix)/include/
+CFLAGS          = -O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER -DCOMMON_PTHREAD -DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_GZ -DIDXSIZE64
+CLIBFLAGS       = -shared -fPIC
+LDFLAGS         = -lz -lm -pthread
+CP              = cp
+LEX             = flex -Pscotchyy -olex.yy.c
+LN              = ln
+MKDIR           = mkdir -p
+MV              = mv
+RANLIB          = echo
+YACC            = bison -pscotchyy -y -b y
