--- ../xictools-master/Makefile	2024-02-23 08:47:58.384498499 -0500
+++ Makefile	2024-02-23 08:55:56.681812877 -0500
@@ -31,7 +31,7 @@
 # all files in their local space with the PREFIX variable set
 # appropriately and this variable set to "yes" instead of "no".
 #
-ITOPOK = --enable-itopok=no
+ITOPOK = --enable-itopok=yes
 
 # The licensing system for Xic and WRspice is disabled by default, but
 # can be enabled by uncommenting the assignment below.  The code for
@@ -81,7 +81,7 @@
 #GFXLOC = --enable-qt5=/opt/local/libexec/qt5
 #GFXLOC = --enable-qt5=/usr/lib64/qt5
 #GFXLOC = --enable-qt5=yes
-GFXLOC = --enable-gtk2=yes
+#GFXLOC = --enable-gtk2=yes
 
 # OpenAccess support, Linux only.
 # If you have an OpenAccess source tree, specify its location in this
