--- a/Makefile
+++ b/Makefile
@@ -26,7 +26,7 @@
 # their local space with the PREFIX variable set appropriately and
 # this variable set to "yes" instead of "no".
 #
-ITOPOK = --enable-itopok=no
+ITOPOK = --enable-itopok=yes
 
