#pragma once

#include "jlcxx/array.hpp"
#include "jlcxx/jlcxx.hpp"
#include "jlcxx/tuple.hpp"

std::tuple<double,
           int,
           int,
           jlcxx::Array<std::int64_t>,
           jlcxx::Array<double>,
           jlcxx::Array<std::int64_t>,
           jlcxx::Array<double>,
           jlcxx::Array<double>,
           jlcxx::Array<double>,
           jlcxx::Array<double>>
cv_slope_dense(jlcxx::ArrayRef<double, 2> x_in,
               jlcxx::ArrayRef<double, 1> y_in,
               jlcxx::ArrayRef<double, 1> alpha_in,
               jlcxx::ArrayRef<double, 1> lambda_in,
               std::int64_t n,
               std::int64_t p,
               std::int64_t m,
               bool fit_intercept,
               std::string loss_type,
               std::string centering_type,
               std::string scaling_type,
               std::size_t path_length,
               double tol,
               std::int64_t max_it,
               double q,
               std::int64_t max_clusters,
               double dev_change_tol,
               double dev_ratio_tol,
               double alpha_min_ratio,
               std::int64_t n_folds,
               std::int64_t n_repeats,
               std::string metric,
               std::vector<double> q_cv,
               std::vector<double> gamma_cv,
               std::vector<std::int64_t> fold_indices);

std::tuple<double,
           int,
           int,
           jlcxx::Array<std::int64_t>,
           jlcxx::Array<double>,
           jlcxx::Array<std::int64_t>,
           jlcxx::Array<double>,
           jlcxx::Array<double>,
           jlcxx::Array<double>,
           jlcxx::Array<double>>
cv_slope_sparse(jlcxx::ArrayRef<std::int64_t, 1> x_colptr,
                jlcxx::ArrayRef<std::int64_t, 1> x_rowval,
                jlcxx::ArrayRef<double, 1> x_vals,
                jlcxx::ArrayRef<double, 1> y_in,
                jlcxx::ArrayRef<double, 1> alpha_in,
                jlcxx::ArrayRef<double, 1> lambda_in,
                std::int64_t n,
                std::int64_t p,
                std::int64_t m,
                bool fit_intercept,
                std::string loss_type,
                std::string centering_type,
                std::string scaling_type,
                std::size_t path_length,
                double tol,
                std::int64_t max_it,
                double q,
                std::int64_t max_clusters,
                double dev_change_tol,
                double dev_ratio_tol,
                double alpha_min_ratio,
                std::int64_t n_folds,
                std::int64_t n_repeats,
                std::string metric,
                std::vector<double> q_cv,
                std::vector<double> gamma_cv,
                std::vector<std::int64_t> fold_indices);
