# Aurora dgpu LTS 2523.40.
#
# Per-package pins for this point release:
#   https://dgpu-docs.osgc.infra-host.com/releases/packages.html?release=LTS+2523.40&os=all
# General LTS line tracking:
#   https://docs.alcf.anl.gov/aurora/system-updates/
#   https://dgpu-docs.osgc.infra-host.com/releases/release-notes.html
#
# This file is FROZEN to LTS 2523.40. When Aurora ticks to 2523.41 (or 2524.x,
# or a new LTS line), fork a parallel `common_lts_<line>_<patch>.jl` and a
# fresh pair of `@LTS_<line>.<patch>/` recipe dirs — do not edit this file.
# Each Aurora point release becomes its own JLL so users pinning to 2523.40
# get bit-identical behavior across rebuilds.

version     = v"1.24.0"   # libze1 / libze-dev shipped in LTS 2523.40
api_version = v"1.13.0"   # ZE_API_VERSION_CURRENT at v1.24.0 (frozen for 2523)

sources = BinaryBuilder.AbstractSource[
    GitSource("https://github.com/oneapi-src/level-zero.git",
              "9402907a3ce6987871325e4e1329e053b8e5cf2b"),  # tag v1.24.0
]
