# Note that this script can accept some limited command-line arguments, run
# `julia build_tarballs.jl --help` to see a usage message.
using BinaryBuilder, Pkg

const YGGDRASIL_DIR = "../.."
include(joinpath(YGGDRASIL_DIR, "platforms", "macos_sdks.jl"))

name = "iroh"
version = v"0.101.0"

# Collection of sources required to complete build
sources = [
    # The C FFI bindings for iroh (https://github.com/n0-computer/iroh) live in
    # their own repository, versioned in lock-step with `iroh` itself.
    # Tag v0.101.0
    GitSource("https://github.com/n0-computer/iroh-c-ffi.git",
              "e49b57881af2b5bc787f00bec7982de94d0e7394"),
]

# Bash recipe for building across all platforms
script = raw"""
cd ${WORKSPACE}/srcdir/iroh-c-ffi

install_license LICENSE-MIT LICENSE-APACHE

# `ring` (pulled in via rustls/quinn) compiles a bit of C in its build script.
# Point the host compiler at the build compiler so that the native code path
# works while cross-compiling (see Z/ZenohC, which has the same dependency).
export CC_$(echo ${rust_host} | sed "s/-/_/g")=${CC_BUILD}

# musl targets default to a static CRT, which makes it impossible to produce a
# `cdylib`.  Turn that off.
if [[ "${target}" == *-musl* ]]; then
    export RUSTFLAGS="-C target-feature=-crt-static"
fi

# The crate declares crate-type = ["staticlib", "cdylib", "lib"]; ask for just
# the cdylib so that we don't pay for building the static library as well.
cargo rustc --release --lib --crate-type=cdylib

# `libiroh_c_ffi.{so,dylib}` on Unix, `iroh_c_ffi.dll` on Windows.
install -Dvm 755 target/${rust_target}/release/*iroh_c_ffi.${dlext} -t "${libdir}"

# The C header is generated by `cargo run --features headers --bin
# generate_headers`, which cannot run while cross-compiling.  Upstream checks
# the generated header into the repository and its CI fails if it ever drifts
# from the generator output, so we install the checked-in copy.
install -Dvm 644 irohnet.h "${includedir}/irohnet.h"
"""

# `reqwest` pulls in `rustls-platform-verifier` -> `security-framework`, which
# calls `SecTrustEvaluateWithError()`.  That symbol was introduced in macOS
# 10.14, so the default 10.12 SDK used for `x86_64-apple-darwin14` fails to
# link.  Use the same SDK the aarch64 builder already uses (11.1); the helper
# is a no-op on aarch64 for exactly that reason.  The deployment target is kept
# lower than the SDK so we don't needlessly raise the minimum macOS version.
sources, script = require_macos_sdk("11.1", sources, script; deployment_target = "10.15")

# These are the platforms we will build for by default, unless further
# platforms are passed in on the command line
platforms = supported_platforms()

# The Rust toolchain for 32-bit Windows is unusable
# (https://github.com/rust-lang/rust/issues/79609)
filter!(p -> !(Sys.iswindows(p) && arch(p) == "i686"), platforms)

# `ring` only ships assembly (and CPU feature detection) for x86, x86_64, arm
# and aarch64.
filter!(p -> arch(p) ∈ ("x86_64", "i686", "aarch64", "armv7l", "armv6l"), platforms)

# The products that we will ensure are always built
products = [
    LibraryProduct(["libiroh_c_ffi", "iroh_c_ffi"], :libiroh_c_ffi),
    FileProduct("include/irohnet.h", :irohnet_h),
]

# Dependencies that must be installed before this package can be built
dependencies = Dependency[]

# Build the tarballs, and possibly a `build.jl` as well.
build_tarballs(ARGS, name, version, sources, script, platforms, products, dependencies;
               julia_compat = "1.10", compilers = [:c, :rust],
               preferred_gcc_version = v"10", lock_microarchitecture = false)
