diff --git a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -282,7 +282,7 @@ JL_PRIVATE_LIBS-0 += libgfortran libgcc_s libquadmath
 endif
 
 
-install: $(build_depsbindir)/stringreplace $(BUILDROOT)/doc/_build/html/en/index.html
+install: $(build_depsbindir)/stringreplace
 ifeq ($(BUNDLE_DEBUG_LIBS),1)
 	@$(MAKE) $(QUIET_MAKE) all
 else
@@ -356,34 +356,6 @@ endif
 
 	# Copy public headers
 	cp -R -L $(build_includedir)/julia/* $(DESTDIR)$(includedir)/julia
-	# Copy system image
-	$(INSTALL_M) $(build_private_libdir)/sys.$(SHLIB_EXT) $(DESTDIR)$(private_libdir)
-ifeq ($(BUNDLE_DEBUG_LIBS),1)
-	$(INSTALL_M) $(build_private_libdir)/sys-debug.$(SHLIB_EXT) $(DESTDIR)$(private_libdir)
-endif
-
-	# Copy in all .jl sources as well
-	mkdir -p $(DESTDIR)$(datarootdir)/julia/base $(DESTDIR)$(datarootdir)/julia/test
-	cp -R -L $(JULIAHOME)/base/* $(DESTDIR)$(datarootdir)/julia/base
-	cp -R -L $(JULIAHOME)/test/* $(DESTDIR)$(datarootdir)/julia/test
-	cp -R -L $(build_datarootdir)/julia/* $(DESTDIR)$(datarootdir)/julia
-	# Copy documentation
-	cp -R -L $(BUILDROOT)/doc/_build/html $(DESTDIR)$(docdir)/
-	# Remove various files which should not be installed
-	-rm -f $(DESTDIR)$(datarootdir)/julia/base/version_git.sh
-	-rm -f $(DESTDIR)$(datarootdir)/julia/test/Makefile
-	-rm -f $(DESTDIR)$(datarootdir)/julia/stdlib/$(VERSDIR)/*/source-extracted
-	-rm -f $(DESTDIR)$(datarootdir)/julia/stdlib/$(VERSDIR)/*/build-configured
-	-rm -f $(DESTDIR)$(datarootdir)/julia/stdlib/$(VERSDIR)/*/build-compiled
-	-rm -f $(DESTDIR)$(datarootdir)/julia/stdlib/$(VERSDIR)/*/build-checked
-	# Copy in beautiful new man page
-	$(INSTALL_F) $(build_man1dir)/julia.1 $(DESTDIR)$(man1dir)/
-	# Copy .desktop file
-	mkdir -p $(DESTDIR)$(datarootdir)/applications/
-	$(INSTALL_F) $(JULIAHOME)/contrib/julia.desktop $(DESTDIR)$(datarootdir)/applications/
-	# Install appdata file
-	mkdir -p $(DESTDIR)$(datarootdir)/appdata/
-	$(INSTALL_F) $(JULIAHOME)/contrib/julia.appdata.xml $(DESTDIR)$(datarootdir)/appdata/
 
 	# Update RPATH entries and JL_SYSTEM_IMAGE_PATH if $(private_libdir_rel) != $(build_private_libdir_rel)
 ifneq ($(private_libdir_rel),$(build_private_libdir_rel))
