#!/bin/bash
args=$(echo '' "$@" '')
args_modified=$(echo '' "$@" '' | sed -e 's/ -Ofast / -O3 -fexcess-precision=fast -fno-math-errno /g;s/ -ffast-math / -fexcess-precision=fast -fno-math-errno /g;s/ -funsafe-math-optimizations / /g;s/ -march=[^ ]* / /g;s/ -maes / /g;s/ -msse4[.]1 / /g;s/ -Xarch_[^ ]* / /g')
if [[ "$args" != "$args_modified" ]]; then
    echo "$0 modified arguments: \"$args\" to \"$args_modified\""
fi
exec cc $args_modified
